"""Word pools for the drawing game."""

DRAW_CATEGORIES = {
    "animals": [
        {"word_en": "cat", "word_ar": "قطة", "aliases_en": ["kitty"], "aliases_ar": ["بسة", "قط"], "difficulty": "easy"},
        {"word_en": "dog", "word_ar": "كلب", "aliases_en": ["puppy"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "lion", "word_ar": "أسد", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "tiger", "word_ar": "نمر", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "elephant", "word_ar": "فيل", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "giraffe", "word_ar": "زرافة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "zebra", "word_ar": "حمار وحشي", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "monkey", "word_ar": "قرد", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bear", "word_ar": "دب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "wolf", "word_ar": "ذئب", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "fox", "word_ar": "ثعلب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "rabbit", "word_ar": "أرنب", "aliases_en": ["bunny"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cow", "word_ar": "بقرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "horse", "word_ar": "حصان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "sheep", "word_ar": "خروف", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "goat", "word_ar": "ماعز", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "chicken", "word_ar": "دجاجة", "aliases_en": ["hen"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "duck", "word_ar": "بطة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "eagle", "word_ar": "نسر", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "shark", "word_ar": "قرش", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "whale", "word_ar": "حوت", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "dolphin", "word_ar": "دلفين", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "octopus", "word_ar": "أخطبوط", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "snake", "word_ar": "ثعبان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "lizard", "word_ar": "سحلية", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "frog", "word_ar": "ضفدع", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "penguin", "word_ar": "بطريق", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "kangaroo", "word_ar": "كنغر", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "panda", "word_ar": "باندا", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "camel", "word_ar": "جمل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
    ],

    "objects": [
        {"word_en": "book", "word_ar": "كتاب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pen", "word_ar": "قلم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pencil", "word_ar": "قلم رصاص", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "eraser", "word_ar": "ممحاة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "microscope", "word_ar": "مجهر", "aliases_en": [], "aliases_ar": [], "difficulty": "hard"},
        {"word_en": "door", "word_ar": "باب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "window", "word_ar": "نافذة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "table", "word_ar": "طاولة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "chair", "word_ar": "كرسي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "sofa", "word_ar": "كنبة", "aliases_en": ["couch"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bed", "word_ar": "سرير", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pillow", "word_ar": "وسادة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "blanket", "word_ar": "بطانية", "aliases_en": [], "aliases_ar": ["حرام", "لحاف"], "difficulty": "easy"},
        {"word_en": "carpet", "word_ar": "سجادة", "aliases_en": ["rug"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "curtain", "word_ar": "ستارة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "mirror", "word_ar": "مرآة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "clock", "word_ar": "ساعة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "lamp", "word_ar": "مصباح", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "light", "word_ar": "ضوء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "fan", "word_ar": "مروحة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "fridge", "word_ar": "ثلاجة", "aliases_en": ["refrigerator"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "oven", "word_ar": "فرن", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "microwave", "word_ar": "ميكروويف", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "sink", "word_ar": "حوض", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "tap", "word_ar": "حنفية", "aliases_en": ["faucet"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "plate", "word_ar": "صحن", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cup", "word_ar": "كوب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "spoon", "word_ar": "ملعقة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "fork", "word_ar": "شوكة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "knife", "word_ar": "سكين", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "book", "word_ar": "كتاب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pen", "word_ar": "قلم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "notebook", "word_ar": "دفتر", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "phone", "word_ar": "هاتف", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "charger", "word_ar": "شاحن", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "trash can", "word_ar": "سلة مهملات", "aliases_en": ["bin"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "broom", "word_ar": "مكنسة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bucket", "word_ar": "دلو", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "soap", "word_ar": "صابون", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "towel", "word_ar": "منشفة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "wardrobe", "word_ar": "خزانة ملابس", "aliases_en": ["closet"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "drawer", "word_ar": "درج", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "shelf", "word_ar": "رف", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cabinet", "word_ar": "خزانة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "tv", "word_ar": "تلفاز", "aliases_en": ["television"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "remote", "word_ar": "ريموت", "aliases_en": ["remote control"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "painting", "word_ar": "لوحة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "photo frame", "word_ar": "إطار صورة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "vase", "word_ar": "مزهرية", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "plant", "word_ar": "نبتة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "mirror cabinet", "word_ar": "خزانة مرآة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "shower", "word_ar": "دش", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "toilet", "word_ar": "مرحاض", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "toothbrush", "word_ar": "فرشاة أسنان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "toothpaste", "word_ar": "معجون أسنان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "sponge", "word_ar": "إسفنجة", "aliases_en": [], "aliases_ar": ["ليفه"], "difficulty": "easy"},
        {"word_en": "trash bag", "word_ar": "كيس قمامة", "aliases_en": [], "aliases_ar": ["كيس زبالة"], "difficulty": "easy"},
        {"word_en": "iron", "word_ar": "مكواة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "stairs", "word_ar": "درج", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "doorbell", "word_ar": "جرس الباب", "aliases_en": [], "aliases_ar": ["جرس"], "difficulty": "easy"},
        {"word_en": "lock", "word_ar": "قفل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "key", "word_ar": "مفتاح", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "wallet", "word_ar": "محفظة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"}
    ],

    "general_sports": [
        {"word_en": "goal", "word_ar": "هدف", "aliases_en": [], "aliases_ar": ["غول"], "difficulty": "easy"},
        {"word_en": "ball", "word_ar": "كرة", "aliases_en": [], "aliases_ar": ["طابة"], "difficulty": "easy"},
        {"word_en": "goalkeeper", "word_ar": "حارس مرمى", "aliases_en": ["keeper", "goalie"], "aliases_ar": ["حارس"], "difficulty": "medium"},
        {"word_en": "defender", "word_ar": "مدافع", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "midfielder", "word_ar": "لاعب وسط", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "striker", "word_ar": "مهاجم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "penalty", "word_ar": "ضربة جزاء", "aliases_en": ["pen"], "aliases_ar": ["جزاء", "بلنتي"], "difficulty": "easy"},
        {"word_en": "offside", "word_ar": "تسلل", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "corner", "word_ar": "ركنية", "aliases_en": ["corner kick"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "free kick", "word_ar": "ضربة حرة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "referee", "word_ar": "حكم", "aliases_en": ["ref"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "yellow card", "word_ar": "بطاقة صفراء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "red card", "word_ar": "بطاقة حمراء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "stadium", "word_ar": "ملعب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "fan", "word_ar": "مشجع", "aliases_en": ["supporter"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "coach", "word_ar": "مدرب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "team", "word_ar": "فريق", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pass", "word_ar": "تمريرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "dribble", "word_ar": "مراوغة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "shoot", "word_ar": "تسديدة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "header", "word_ar": "ضربة رأس", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "tackle", "word_ar": "افتكاك", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "league", "word_ar": "دوري", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "champions league", "word_ar": "دوري الأبطال", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "substitution", "word_ar": "تبديل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "injury", "word_ar": "إصابة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "whistle", "word_ar": "صافرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "kickoff", "word_ar": "بداية المباراة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "extra time", "word_ar": "وقت إضافي", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "final", "word_ar": "نهائي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cup", "word_ar": "كأس", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "medal", "word_ar": "ميدالية", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "racket", "word_ar": "مضرب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "rope", "word_ar": "حبل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "basket", "word_ar": "سلة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "shoe", "word_ar": "حذاء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "helmet", "word_ar": "خوذة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "running", "word_ar": "ركض", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "jumping", "word_ar": "قفز", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "walking", "word_ar": "مشي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "swimming", "word_ar": "سباحة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "kicking", "word_ar": "ركل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "throwing", "word_ar": "رمي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "falling", "word_ar": "سقوط", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "balance", "word_ar": "توازن", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "pushing", "word_ar": "دفع", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pulling", "word_ar": "سحب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "tennis", "word_ar": "تنس", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "judo", "word_ar": "جودو", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "yoga", "word_ar": "يوغا", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "golf", "word_ar": "جولف", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "boxing", "word_ar": "ملاكمة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "ballet", "word_ar": "باليه", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "diving", "word_ar": "غوص", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "skating", "word_ar": "تزلج", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "shooting", "word_ar": "رماية", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "running_race", "word_ar": "جري", "aliases_en": ["sprint"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pool", "word_ar": "مسبح", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "arena", "word_ar": "حلبة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "club", "word_ar": "نادي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "flag", "word_ar": "علم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "torch", "word_ar": "شعلة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "podium", "word_ar": "منصة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "net", "word_ar": "شباك", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "scale", "word_ar": "ميزان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "watch", "word_ar": "ساعة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "shirt", "word_ar": "قميص", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "hat", "word_ar": "قبعة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "glove", "word_ar": "قفاز", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bag", "word_ar": "حقيبة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bicycle", "word_ar": "دراجة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "board", "word_ar": "لوح", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "weight", "word_ar": "ثقل", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "arrow", "word_ar": "سهم", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "bow", "word_ar": "قوس", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "banner", "word_ar": "راية", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"}
    ],

    "pc_setup": [
        {"word_en": "monitor", "word_ar": "شاشة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "keyboard", "word_ar": "كيبورد", "aliases_en": [], "aliases_ar": ["لوحة مفاتيح"], "difficulty": "easy"},
        {"word_en": "mouse", "word_ar": "ماوس", "aliases_en": [], "aliases_ar": ["فأرة"], "difficulty": "easy"},
        {"word_en": "headset", "word_ar": "سماعة", "aliases_en": ["headphones"], "aliases_ar": ["سماعات"], "difficulty": "easy"},
        {"word_en": "webcam", "word_ar": "كاميرا", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "microphone", "word_ar": "ميكروفون", "aliases_en": ["mic"], "aliases_ar": ["مايك"], "difficulty": "easy"},
        {"word_en": "desk", "word_ar": "مكتب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "chair", "word_ar": "كرسي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "mousepad", "word_ar": "ماوس باد", "aliases_en": ["mouse mat"], "aliases_ar": ["بساط ماوس"], "difficulty": "easy"},
        {"word_en": "pc case", "word_ar": "صندوق الكمبيوتر", "aliases_en": ["case"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "graphics card", "word_ar": "كرت شاشة", "aliases_en": ["gpu"], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "processor", "word_ar": "معالج", "aliases_en": ["cpu"], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "ram", "word_ar": "رام", "aliases_en": ["memory"], "aliases_ar": ["ذاكرة"], "difficulty": "medium"},
        {"word_en": "ssd", "word_ar": "قرص SSD", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "hard drive", "word_ar": "هارد", "aliases_en": ["hdd"], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "power supply", "word_ar": "مزود طاقة", "aliases_en": ["psu"], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "cooler", "word_ar": "مبرد", "aliases_en": ["fan"], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "rgb lights", "word_ar": "إضاءة RGB", "aliases_en": ["rgb"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cables", "word_ar": "كابلات", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "usb hub", "word_ar": "USB", "aliases_en": [], "aliases_ar": ["يو اس بي"], "difficulty": "easy"},
        {"word_en": "external drive", "word_ar": "هارد خارجي", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "router", "word_ar": "راوتر", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "ethernet cable", "word_ar": "كابل انترنت", "aliases_en": ["lan cable"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "desk lamp", "word_ar": "لمبة مكتب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "controller", "word_ar": "يد تحكم", "aliases_en": ["gamepad"], "aliases_ar": ["قبضة"], "difficulty": "easy"},
        {"word_en": "console", "word_ar": "كونسول", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "green screen", "word_ar": "خلفية خضراء", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "tripod", "word_ar": "حامل كاميرا", "aliases_en": [], "aliases_ar": ["حامل ثلاثي"], "difficulty": "easy"}
    ],

    "syrian_series": [
        {"word_en": "Bab Al Hara", "word_ar": "باب الحارة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Dayaa Dayaa", "word_ar": "ضيعة ضايعة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Kharba", "word_ar": "الخربة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Buqaat Daw", "word_ar": "بقعة ضوء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Yawmiyat Mudir Aam", "word_ar": "يوميات مدير عام", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Fusul Al Arbaa", "word_ar": "الفصول الأربعة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Nadam", "word_ar": "الندم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Hayba", "word_ar": "الهيبة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Wilada Min Al Khasira", "word_ar": "الولادة من الخاصرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Inaya Mushadada", "word_ar": "عناية مشددة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Ahl Al Gharam", "word_ar": "أهل الغرام", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Takht Sharqi", "word_ar": "تخت شرقي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Layali Al Salihiya", "word_ar": "ليالي الصالحية", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Aarabji", "word_ar": "العربجي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Kaser Adhm", "word_ar": "كسر عضم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Zend", "word_ar": "الزند", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Haroun Al Rashid", "word_ar": "هارون الرشيد", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Taht Sabea Ard", "word_ar": "تحت سابع أرض", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Sabaa", "word_ar": "السبع", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Nasmaat Ayloul ", "word_ar": "نسمات أيلول", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Al Ameel", "word_ar": "العميل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Ayam Al Dirasa", "word_ar": "أيام الدراسة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Haroun", "word_ar": "هارون", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Tawq Al Banat", "word_ar": "طوق البنات", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Moulana", "word_ar": "مولانا", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Zaman Al Barghout", "word_ar": "زمن البرغوث", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Haret Al Qobba", "word_ar": "حارة القبة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "Qamar Sham", "word_ar": "قمر شام", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
    ],
}