"""Word pools for the drawing game."""

DRAW_CATEGORIES = {
    "animals": [
        {"word_en": "cat", "word_ar": "قطة", "aliases_en": ["kitty"], "aliases_ar": ["بسة", "قط"], "difficulty": "easy"},
        {"word_en": "dog", "word_ar": "كلب", "aliases_en": ["puppy"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "lion", "word_ar": "أسد", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "tiger", "word_ar": "نمر", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "elephant", "word_ar": "فيل", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "giraffe", "word_ar": "زرافة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "zebra", "word_ar": "حمار وحشي", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "monkey", "word_ar": "قرد", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bear", "word_ar": "دب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "wolf", "word_ar": "ذئب", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "fox", "word_ar": "ثعلب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "rabbit", "word_ar": "أرنب", "aliases_en": ["bunny"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cow", "word_ar": "بقرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "horse", "word_ar": "حصان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "sheep", "word_ar": "خروف", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "goat", "word_ar": "ماعز", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "chicken", "word_ar": "دجاجة", "aliases_en": ["hen"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "duck", "word_ar": "بطة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "eagle", "word_ar": "نسر", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "shark", "word_ar": "قرش", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "whale", "word_ar": "حوت", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "dolphin", "word_ar": "دلفين", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "octopus", "word_ar": "أخطبوط", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "snake", "word_ar": "ثعبان", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "lizard", "word_ar": "سحلية", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "frog", "word_ar": "ضفدع", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "penguin", "word_ar": "بطريق", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "kangaroo", "word_ar": "كنغر", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "panda", "word_ar": "باندا", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "camel", "word_ar": "جمل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
    ],

    "objects": [
        {"word_en": "chair", "word_ar": "كرسي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "table", "word_ar": "طاولة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bed", "word_ar": "سرير", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "sofa", "word_ar": "كنبة", "aliases_en": ["couch"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "lamp", "word_ar": "مصباح", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "phone", "word_ar": "هاتف", "aliases_en": ["mobile"], "aliases_ar": ["جوال"], "difficulty": "easy"},
        {"word_en": "laptop", "word_ar": "لابتوب", "aliases_en": ["computer"], "aliases_ar": ["حاسوب"], "difficulty": "easy"},
        {"word_en": "keyboard", "word_ar": "لوحة مفاتيح", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "mouse", "word_ar": "فأرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "screen", "word_ar": "شاشة", "aliases_en": ["monitor"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "book", "word_ar": "كتاب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pen", "word_ar": "قلم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pencil", "word_ar": "قلم رصاص", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "eraser", "word_ar": "ممحاة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bag", "word_ar": "حقيبة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "watch", "word_ar": "ساعة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "glasses", "word_ar": "نظارات", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "bottle", "word_ar": "زجاجة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "cup", "word_ar": "كوب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "plate", "word_ar": "طبق", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "knife", "word_ar": "سكين", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "fork", "word_ar": "شوكة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "spoon", "word_ar": "ملعقة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "scissors", "word_ar": "مقص", "aliases_en": ["scissor"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "camera", "word_ar": "كاميرا", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "television", "word_ar": "تلفاز", "aliases_en": ["tv"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "door", "word_ar": "باب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "window", "word_ar": "نافذة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "mirror", "word_ar": "مرآة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "microscope", "word_ar": "مجهر", "aliases_en": [], "aliases_ar": [], "difficulty": "hard"},
    ],

    "football": [
        {"word_en": "goal", "word_ar": "هدف", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "ball", "word_ar": "كرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "goalkeeper", "word_ar": "حارس مرمى", "aliases_en": ["keeper", "goalie"], "aliases_ar": ["حارس"], "difficulty": "medium"},
        {"word_en": "defender", "word_ar": "مدافع", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "midfielder", "word_ar": "لاعب وسط", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "striker", "word_ar": "مهاجم", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "penalty", "word_ar": "ضربة جزاء", "aliases_en": ["pen"], "aliases_ar": ["جزاء", "بلنتي"], "difficulty": "easy"},
        {"word_en": "offside", "word_ar": "تسلل", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "corner", "word_ar": "ركنية", "aliases_en": ["corner kick"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "free kick", "word_ar": "ضربة حرة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "referee", "word_ar": "حكم", "aliases_en": ["ref"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "yellow card", "word_ar": "بطاقة صفراء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "red card", "word_ar": "بطاقة حمراء", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "stadium", "word_ar": "ملعب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "fan", "word_ar": "مشجع", "aliases_en": ["supporter"], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "coach", "word_ar": "مدرب", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "team", "word_ar": "فريق", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "pass", "word_ar": "تمريرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "dribble", "word_ar": "مراوغة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "shoot", "word_ar": "تسديدة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "header", "word_ar": "ضربة رأس", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "tackle", "word_ar": "افتكاك", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "league", "word_ar": "دوري", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "champions league", "word_ar": "دوري الأبطال", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "substitution", "word_ar": "تبديل", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "injury", "word_ar": "إصابة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "whistle", "word_ar": "صافرة", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
        {"word_en": "kickoff", "word_ar": "بداية المباراة", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "extra time", "word_ar": "وقت إضافي", "aliases_en": [], "aliases_ar": [], "difficulty": "medium"},
        {"word_en": "final", "word_ar": "نهائي", "aliases_en": [], "aliases_ar": [], "difficulty": "easy"},
    ],
}