CATEGORIES = {
    "football_players": [
        {"label": "ليونيل ميسي", "aliases": ["ميسي", "ليونيل", "messi", "lionel messi"]},
        {"label": "كريستيانو رونالدو", "aliases": ["رونالدو", "كريستيانو", "cristiano", "ronaldo"]},
        {"label": "محمد صلاح", "aliases": ["صلاح", "mohamed salah", "salah"]},
        {"label": "كيليان مبابي", "aliases": ["مبابي", "mbappe", "kylian mbappe"]},
        {"label": "نيمار", "aliases": ["neymar"]},
        {"label": "لوكا مودريتش", "aliases": ["مودريتش", "modric"]},
        {"label": "روبرت ليفاندوفسكي", "aliases": ["ليفاندوفسكي", "lewandowski"]},
        {"label": "إيرلينغ هالاند", "aliases": ["هالاند", "haaland"]},
        {"label": "كريم بنزيما", "aliases": ["بنزيما", "benzema"]},
        {"label": "رونالدينيو", "aliases": ["ronaldinho"]},
        {"label": "زين الدين زيدان", "aliases": ["زيدان", "zidane"]},
        {"label": "تشافي", "aliases": ["xavi"]},
        {"label": "إنييستا", "aliases": ["iniesta"]},
        {"label": "سيرجيو راموس", "aliases": ["راموس", "ramos"]},
        {"label": "جيرارد بيكيه", "aliases": ["بيكيه", "pique"]},
        {"label": "لويس سواريز", "aliases": ["سواريز", "suarez"]},
        {"label": "سيرجيو أغويرو", "aliases": ["اغويرو", "aguero"]},
        {"label": "تييري هنري", "aliases": ["هنري", "henry"]},
        {"label": "ديفيد بيكهام", "aliases": ["بيكهام", "beckham"]},
        {"label": "واين روني", "aliases": ["روني", "rooney"]},
        {"label": "ستيفن جيرارد", "aliases": ["جيرارد", "gerrard"]},
        {"label": "فرانك لامبارد", "aliases": ["لامبارد", "lampard"]},
        {"label": "أندريا بيرلو", "aliases": ["بيرلو", "pirlo"]},
        {"label": "جيانلويجي بوفون", "aliases": ["بوفون", "buffon"]},
        {"label": "إيكر كاسياس", "aliases": ["كاسياس", "casillas"]},
        {"label": "مانويل نوير", "aliases": ["نوير", "neuer"]},
        {"label": "توني كروس", "aliases": ["كروس", "kroos"]},
        {"label": "توماس مولر", "aliases": ["مولر", "muller"]},
        {"label": "ماركو رويس", "aliases": ["رويس", "reus"]},
        {"label": "إيدين هازارد", "aliases": ["هازارد", "hazard"]},
        {"label": "كيفين دي بروين", "aliases": ["دي بروين", "de bruyne"]},
        {"label": "تيبو كورتوا", "aliases": ["كورتوا", "courtois"]},
        {"label": "هاري كين", "aliases": ["كين", "kane"]},
        {"label": "سون هيونغ مين", "aliases": ["سون", "son"]},
        {"label": "غاريث بيل", "aliases": ["بيل", "bale"]},
        {"label": "فرانك ريبيري", "aliases": ["ريبيري", "ribery"]},
        {"label": "آريين روبن", "aliases": ["روبن", "robben"]},
        {"label": "صامويل إيتو", "aliases": ["ايتو", "eto"]},
        {"label": "ديدييه دروغبا", "aliases": ["دروغبا", "drogba"]},
        {"label": "يايا توريه", "aliases": ["توريه", "yaya toure"]},
        {"label": "كاكا", "aliases": ["kaka"]},
        {"label": "ريفالدو", "aliases": ["rivaldo"]},
        {"label": "روماريو", "aliases": ["romario"]},
        {"label": "رونالدو نازاريو", "aliases": ["الظاهرة", "ronaldo"]},
        {"label": "دييغو مارادونا", "aliases": ["مارادونا", "maradona"]},
        {"label": "بيليه", "aliases": ["pele"]},
        {"label": "ميشيل بلاتيني", "aliases": ["بلاتيني", "platini"]},
        {"label": "روبرتو باجيو", "aliases": ["باجيو", "baggio"]},
        {"label": "أليساندرو ديل بييرو", "aliases": ["ديل بييرو", "del piero"]},
        {"label": "فرانشيسكو توتي", "aliases": ["توتي", "totti"]},
        {"label": "أليساندرو نيستا", "aliases": ["نيستا", "nesta"]},
        {"label": "باولو مالديني", "aliases": ["مالديني", "maldini"]},
        {"label": "فابيو كانافارو", "aliases": ["كانافارو", "cannavaro"]},
        {"label": "جورجيو كيليني", "aliases": ["كيليني", "chiellini"]},
        {"label": "ليوناردو بونوتشي", "aliases": ["بونوتشي", "bonucci"]},
        {"label": "داني ألفيس", "aliases": ["الفيس", "dani alves"]},
        {"label": "مارسيلو", "aliases": ["marcelo"]},
        {"label": "كافو", "aliases": ["cafu"]},
        {"label": "روبرتو كارلوس", "aliases": ["كارلوس", "roberto carlos"]},
        {"label": "ليليان تورام", "aliases": ["تورام", "thuram"]},
        {"label": "باتريك فييرا", "aliases": ["فييرا", "vieira"]},
        {"label": "كلود ماكيليلي", "aliases": ["ماكيليلي", "makelele"]},
        {"label": "مايكل إيسيان", "aliases": ["ايسيان", "essien"]},
        {"label": "باستيان شفاينشتايغر", "aliases": ["شفاينشتايغر", "schweinsteiger"]},
        {"label": "فيليب لام", "aliases": ["لام", "lahm"]},
        {"label": "مايكل بالاك", "aliases": ["بالاك", "ballack"]},
        {"label": "مسعود أوزيل", "aliases": ["اوزيل", "ozil"]},
        {"label": "أليكسيس سانشيز", "aliases": ["سانشيز", "sanchez"]},
        {"label": "أرتورو فيدال", "aliases": ["فيدال", "vidal"]},
        {"label": "إدينسون كافاني", "aliases": ["كافاني", "cavani"]},
        {"label": "دييغو فورلان", "aliases": ["فورلان", "forlan"]},
        {"label": "كارلوس فالديراما", "aliases": ["فالديراما", "valderrama"]},
        {"label": "خاميس رودريغيز", "aliases": ["خاميس", "james rodriguez"]},
        {"label": "راداميل فالكاو", "aliases": ["فالكاو", "falcao"]},
        {"label": "باولو ديبالا", "aliases": ["ديبالا", "dybala"]},
        {"label": "غونزالو هيغواين", "aliases": ["هيغواين", "higuain"]},
        {"label": "أنخيل دي ماريا", "aliases": ["دي ماريا", "di maria"]},
        {"label": "أنطوان غريزمان", "aliases": ["غريزمان", "griezmann"]},
        {"label": "جوشوا كيميتش", "aliases": ["كيميتش", "kimmich"]},
        {"label": "غافي", "aliases": ["gavi"]},
        {"label": "بيدري", "aliases": ["pedri"]},
        {"label": "جود بيلينغهام", "aliases": ["بيلينغهام", "bellingham"]},
        {"label": "فينيسيوس جونيور", "aliases": ["فينيسيوس", "vinicius"]},
        {"label": "رودريغو", "aliases": ["rodrygo"]},
        {"label": "برناردو سيلفا", "aliases": ["سيلفا", "bernardo"]},
        {"label": "روبن دياز", "aliases": ["دياز", "ruben dias"]},
        {"label": "كايل ووكر", "aliases": ["ووكر", "walker"]},
        {"label": "رحيم سترلينغ", "aliases": ["سترلينغ", "sterling"]},
        {"label": "رياض محرز", "aliases": ["محرز", "mahrez"]},
        {"label": "ساديو ماني", "aliases": ["ماني", "mane"]},
        {"label": "كاليدو كوليبالي", "aliases": ["كوليبالي", "koulibaly"]},
        {"label": "فيكتور أوسيمين", "aliases": ["اوسيمين", "osimhen"]},
        {"label": "أشرف حكيمي", "aliases": ["حكيمي", "hakimi"]},
        {"label": "حكيم زياش", "aliases": ["زياش", "ziyech"]},
        {"label": "كريستيان بوليسيتش", "aliases": ["بوليسيتش", "pulisic"]},
        {"label": "ألفونسو ديفيز", "aliases": ["ديفيز", "alphonso davies"]},
        {"label": "فيرجيل فان دايك", "aliases": ["فان دايك", "van dijk"]},
        {"label": "ترنت ألكسندر أرنولد", "aliases": ["ترنت", "arnold"]},
        {"label": "داروين نونيز", "aliases": ["نونيز", "nunez"]},
        {"label": "لاوتارو مارتينيز", "aliases": ["لاوتارو", "lautaro"]},
        {"label": "إنزو فيرنانديز", "aliases": ["إنزو", "enzo"]},
        {"label": "جوليان ألفاريز", "aliases": ["الفاريز", "alvarez"]},
        {"label": "أليكسيس ماك أليستر", "aliases": ["ماك اليستر", "mac allister"]},
    ],
    "countries": [
        {"label": "سوريا", "aliases": ["سوريا", "syria"]},
        {"label": "مصر", "aliases": ["مصر", "egypt"]},
        {"label": "السعودية", "aliases": ["السعودية", "saudi arabia"]},
        {"label": "الإمارات", "aliases": ["الامارات", "uae", "united arab emirates"]},
        {"label": "قطر", "aliases": ["qatar"]},
        {"label": "الكويت", "aliases": ["kuwait"]},
        {"label": "عمان", "aliases": ["oman"]},
        {"label": "اليمن", "aliases": ["yemen"]},
        {"label": "الأردن", "aliases": ["jordan"]},
        {"label": "لبنان", "aliases": ["lebanon"]},
        {"label": "فلسطين", "aliases": ["palestine"]},
        {"label": "العراق", "aliases": ["iraq"]},
        {"label": "المغرب", "aliases": ["morocco"]},
        {"label": "الجزائر", "aliases": ["algeria"]},
        {"label": "تونس", "aliases": ["tunisia"]},
        {"label": "ليبيا", "aliases": ["libya"]},
        {"label": "السودان", "aliases": ["sudan"]},
        {"label": "الصومال", "aliases": ["somalia"]},
        {"label": "جيبوتي", "aliases": ["djibouti"]},
        {"label": "موريتانيا", "aliases": ["mauritania"]},
        {"label": "جزر القمر", "aliases": ["comoros"]},
        {"label": "البحرين", "aliases": ["bahrain"]},
        {"label": "الولايات المتحدة", "aliases": ["امريكا", "usa", "united states"]},
        {"label": "بريطانيا", "aliases": ["uk", "england", "britain"]},
        {"label": "ألمانيا", "aliases": ["germany"]},
        {"label": "فرنسا", "aliases": ["france"]},
        {"label": "إيطاليا", "aliases": ["italy"]},
        {"label": "إسبانيا", "aliases": ["spain"]},
        {"label": "البرتغال", "aliases": ["portugal"]},
        {"label": "هولندا", "aliases": ["netherlands"]},
        {"label": "بلجيكا", "aliases": ["belgium"]},
        {"label": "سويسرا", "aliases": ["switzerland"]},
        {"label": "النمسا", "aliases": ["austria"]},
        {"label": "السويد", "aliases": ["sweden"]},
        {"label": "النرويج", "aliases": ["norway"]},
        {"label": "الدنمارك", "aliases": ["denmark"]},
        {"label": "فنلندا", "aliases": ["finland"]},
        {"label": "روسيا", "aliases": ["russia"]},
        {"label": "أوكرانيا", "aliases": ["ukraine"]},
        {"label": "بولندا", "aliases": ["poland"]},
        {"label": "رومانيا", "aliases": ["romania"]},
        {"label": "بلغاريا", "aliases": ["bulgaria"]},
        {"label": "اليونان", "aliases": ["greece"]},
        {"label": "تركيا", "aliases": ["turkey"]},
        {"label": "الصين", "aliases": ["china"]},
        {"label": "الهند", "aliases": ["india"]},
        {"label": "اليابان", "aliases": ["japan"]},
        {"label": "كوريا الجنوبية", "aliases": ["south korea"]},
        {"label": "كوريا الشمالية", "aliases": ["north korea"]},
        {"label": "إندونيسيا", "aliases": ["indonesia"]},
        {"label": "ماليزيا", "aliases": ["malaysia"]},
        {"label": "سنغافورة", "aliases": ["singapore"]},
        {"label": "تايلاند", "aliases": ["thailand"]},
        {"label": "فيتنام", "aliases": ["vietnam"]},
        {"label": "الفلبين", "aliases": ["philippines"]},
        {"label": "باكستان", "aliases": ["pakistan"]},
        {"label": "بنغلاديش", "aliases": ["bangladesh"]},
        {"label": "إيران", "aliases": ["iran"]},
        {"label": "كازاخستان", "aliases": ["kazakhstan"]},
        {"label": "أوزبكستان", "aliases": ["uzbekistan"]},
        {"label": "كندا", "aliases": ["canada"]},
        {"label": "المكسيك", "aliases": ["mexico"]},
        {"label": "البرازيل", "aliases": ["brazil"]},
        {"label": "الأرجنتين", "aliases": ["argentina"]},
        {"label": "تشيلي", "aliases": ["chile"]},
        {"label": "بيرو", "aliases": ["peru"]},
        {"label": "كولومبيا", "aliases": ["colombia"]},
        {"label": "فنزويلا", "aliases": ["venezuela"]},
        {"label": "أوروغواي", "aliases": ["uruguay"]},
        {"label": "باراغواي", "aliases": ["paraguay"]},
        {"label": "بوليفيا", "aliases": ["bolivia"]},
        {"label": "كوبا", "aliases": ["cuba"]},
        {"label": "بنما", "aliases": ["panama"]},
        {"label": "كوستاريكا", "aliases": ["costa rica"]},
        {"label": "غواتيمالا", "aliases": ["guatemala"]},
        {"label": "جنوب أفريقيا", "aliases": ["south africa"]},
        {"label": "نيجيريا", "aliases": ["nigeria"]},
        {"label": "كينيا", "aliases": ["kenya"]},
        {"label": "إثيوبيا", "aliases": ["ethiopia"]},
        {"label": "غانا", "aliases": ["ghana"]},
        {"label": "السنغال", "aliases": ["senegal"]},
        {"label": "الكاميرون", "aliases": ["cameroon"]},
        {"label": "ساحل العاج", "aliases": ["ivory coast"]},
        {"label": "أستراليا", "aliases": ["australia"]},
        {"label": "نيوزيلندا", "aliases": ["new zealand"]},
        {"label": "التشيك", "aliases": ["czech republic"]},
        {"label": "سلوفاكيا", "aliases": ["slovakia"]},
        {"label": "المجر", "aliases": ["hungary"]},
        {"label": "صربيا", "aliases": ["serbia"]},
        {"label": "كرواتيا", "aliases": ["croatia"]},
        {"label": "سلوفينيا", "aliases": ["slovenia"]},
        {"label": "البوسنة والهرسك", "aliases": ["bosnia"]},
        {"label": "ألبانيا", "aliases": ["albania"]},
        {"label": "مقدونيا الشمالية", "aliases": ["north macedonia"]},
        {"label": "مونتينيغرو", "aliases": ["montenegro"]},
        {"label": "أيرلندا", "aliases": ["ireland"]},
        {"label": "آيسلندا", "aliases": ["iceland"]},
    ],
    "animals": [
        {"label": "أسد", "aliases": ["اسد", "lion"]},
        {"label": "نمر", "aliases": ["tiger"]},
        {"label": "فهد", "aliases": ["cheetah"]},
        {"label": "فيل", "aliases": ["elephant"]},
        {"label": "زرافة", "aliases": ["giraffe"]},
        {"label": "قرد", "aliases": ["monkey"]},
        {"label": "شمبانزي", "aliases": ["chimpanzee"]},
        {"label": "غوريلا", "aliases": ["gorilla"]},
        {"label": "دب", "aliases": ["bear"]},
        {"label": "باندا", "aliases": ["panda"]},
        {"label": "ذئب", "aliases": ["wolf"]},
        {"label": "ثعلب", "aliases": ["fox"]},
        {"label": "كلب", "aliases": ["dog"]},
        {"label": "قط", "aliases": ["cat"]},
        {"label": "حصان", "aliases": ["horse"]},
        {"label": "حمار", "aliases": ["donkey"]},
        {"label": "بقرة", "aliases": ["cow"]},
        {"label": "ثور", "aliases": ["bull"]},
        {"label": "خروف", "aliases": ["sheep"]},
        {"label": "ماعز", "aliases": ["goat"]},
        {"label": "جمل", "aliases": ["camel"]},
        {"label": "غزال", "aliases": ["gazelle", "deer"]},
        {"label": "كنغر", "aliases": ["kangaroo"]},
        {"label": "كوالا", "aliases": ["koala"]},
        {"label": "تمساح", "aliases": ["crocodile"]},
        {"label": "سلحفاة", "aliases": ["turtle"]},
        {"label": "أفعى", "aliases": ["snake"]},
        {"label": "ضفدع", "aliases": ["frog"]},
        {"label": "قرش", "aliases": ["shark"]},
        {"label": "حوت", "aliases": ["whale"]},
        {"label": "دلفين", "aliases": ["dolphin"]},
        {"label": "أخطبوط", "aliases": ["octopus"]},
        {"label": "نسر", "aliases": ["eagle"]},
        {"label": "صقر", "aliases": ["falcon"]},
        {"label": "بومة", "aliases": ["owl"]},
        {"label": "غراب", "aliases": ["crow"]},
        {"label": "حمامة", "aliases": ["pigeon"]},
        {"label": "ببغاء", "aliases": ["parrot"]},
        {"label": "بط", "aliases": ["duck"]},
        {"label": "دجاج", "aliases": ["chicken"]},
        {"label": "ديك رومي", "aliases": ["turkey"]},
        {"label": "نعامة", "aliases": ["ostrich"]},
        {"label": "بطريق", "aliases": ["penguin"]},
        {"label": "خفاش", "aliases": ["bat"]},
        {"label": "قنفذ", "aliases": ["hedgehog"]},
        {"label": "سنجاب", "aliases": ["squirrel"]},
        {"label": "فأر", "aliases": ["mouse"]},
        {"label": "أرنب", "aliases": ["rabbit"]},
        {"label": "راكون", "aliases": ["raccoon"]},
        {"label": "ضبع", "aliases": ["hyena"]},
        {"label": "حمار وحشي", "aliases": ["zebra"]},
        {"label": "فرس النهر", "aliases": ["hippopotamus"]},
        {"label": "وحيد القرن", "aliases": ["rhinoceros"]},
        {"label": "نمر ثلجي", "aliases": ["snow leopard"]},
        {"label": "فهد أسود", "aliases": ["black panther"]},
        {"label": "بوما", "aliases": ["puma", "cougar"]},
        {"label": "بيسون", "aliases": ["bison"]},
        {"label": "دب قطبي", "aliases": ["polar bear"]},
        {"label": "نحلة", "aliases": ["bee"]},
        {"label": "فراشة", "aliases": ["butterfly"]},
    ],
    "cartoon_characters": [
        {"label": "شريك", "aliases": ["شريك", "shrek"]},
        {"label": "سيمبا", "aliases": ["سيمبا", "simba"]},
        {"label": "ميكي ماوس", "aliases": ["ميكي", "ميكي ماوس", "mickey", "mickey mouse"]},
        {"label": "بطوط", "aliases": ["بطوط", "donald duck", "donald"]},
        {"label": "سكوبي دو", "aliases": ["سكوبي", "سكوبي دو", "scooby", "scooby doo"]},
        {"label": "ناروتو", "aliases": ["naruto"]},
        {"label": "ساسكي", "aliases": ["sasuke"]},
        {"label": "غوكو", "aliases": ["goku"]},
        {"label": "فيجيتا", "aliases": ["vegeta"]},
        {"label": "كابتن ماجد", "aliases": ["tsubasa", "captain majed"]},
        {"label": "بسام", "aliases": ["bassam"]},
        {"label": "وليد", "aliases": ["waleed"]},
        {"label": "عدنان", "aliases": ["adnan"]},
        {"label": "لينا", "aliases": ["lina"]},
        {"label": "سالي", "aliases": ["sally"]},
        {"label": "ريمي", "aliases": ["remi"]},
        {"label": "ماوكلي", "aliases": ["mowgli"]},
        {"label": "سندباد", "aliases": ["sinbad"]},
        {"label": "توم", "aliases": ["tom"]},
        {"label": "جيري", "aliases": ["jerry"]},
        {"label": "سبونج بوب", "aliases": ["spongebob"]},
        {"label": "بسيط", "aliases": ["patrick"]},
        {"label": "ساندي", "aliases": ["sandy"]},
        {"label": "سكوبى دو", "aliases": ["scooby doo"]},
        {"label": "بن تن", "aliases": ["ben 10"]},
        {"label": "كونان", "aliases": ["conan"]},
        {"label": "بيكاتشو", "aliases": ["pikachu"]},
        {"label": "يوغي", "aliases": ["yugi"]},
        {"label": "ميكي ماوس", "aliases": ["mickey mouse"]},
        {"label": "بطوط", "aliases": ["donald duck"]},
        {"label": "تويتي", "aliases": ["tweety"]},
        {"label": "دورا", "aliases": ["dora"]},
        {"label": "دكستر", "aliases": ["dexter"]},
    ],
    "football_clubs": [
        {"label": "ريال مدريد", "aliases": ["real madrid"]},
        {"label": "برشلونة", "aliases": ["barcelona"]},
        {"label": "أتلتيكو مدريد", "aliases": ["atletico madrid"]},
        {"label": "مانشستر يونايتد", "aliases": ["manchester united"]},
        {"label": "مانشستر سيتي", "aliases": ["manchester city"]},
        {"label": "ليفربول", "aliases": ["liverpool"]},
        {"label": "تشيلسي", "aliases": ["chelsea"]},
        {"label": "أرسنال", "aliases": ["arsenal"]},
        {"label": "توتنهام", "aliases": ["tottenham"]},
        {"label": "نيوكاسل", "aliases": ["newcastle"]},
        {"label": "بايرن ميونخ", "aliases": ["bayern munich"]},
        {"label": "بوروسيا دورتموند", "aliases": ["dortmund"]},
        {"label": "لايبزيغ", "aliases": ["leipzig"]},
        {"label": "باير ليفركوزن", "aliases": ["leverkusen"]},
        {"label": "يوفنتوس", "aliases": ["juventus"]},
        {"label": "ميلان", "aliases": ["ac milan"]},
        {"label": "إنتر ميلان", "aliases": ["inter milan"]},
        {"label": "نابولي", "aliases": ["napoli"]},
        {"label": "روما", "aliases": ["roma"]},
        {"label": "لاتسيو", "aliases": ["lazio"]},
        {"label": "باريس سان جيرمان", "aliases": ["psg", "paris saint germain"]},
        {"label": "مارسيليا", "aliases": ["marseille"]},
        {"label": "ليون", "aliases": ["lyon"]},
        {"label": "موناكو", "aliases": ["monaco"]},
        {"label": "ليل", "aliases": ["lille"]},
        {"label": "أياكس", "aliases": ["ajax"]},
        {"label": "أيندهوفن", "aliases": ["psv"]},
        {"label": "فينورد", "aliases": ["feyenoord"]},
        {"label": "بنفيكا", "aliases": ["benfica"]},
        {"label": "بورتو", "aliases": ["porto"]},
        {"label": "سبورتينغ لشبونة", "aliases": ["sporting"]},
        {"label": "سلتيك", "aliases": ["celtic"]},
        {"label": "رينجرز", "aliases": ["rangers"]},
        {"label": "غلطة سراي", "aliases": ["galatasaray"]},
        {"label": "فنربخشة", "aliases": ["fenerbahce"]},
        {"label": "بشكتاش", "aliases": ["besiktas"]},
        {"label": "الهلال", "aliases": ["al hilal"]},
        {"label": "النصر", "aliases": ["al nassr"]},
        {"label": "الاتحاد", "aliases": ["al ittihad"]},
        {"label": "الأهلي", "aliases": ["al ahly"]},
        {"label": "الزمالك", "aliases": ["zamalek"]},
        {"label": "الوداد", "aliases": ["wydad"]},
        {"label": "الرجاء", "aliases": ["raja"]},,
        {"label": "اتلتيك بلباو", "aliases": ["athletic bilbao"]},
        {"label": "ريال سوسيداد", "aliases": ["real sociedad"]},
        {"label": "فالنسيا", "aliases": ["valencia"]},
        {"label": "إشبيلية", "aliases": ["sevilla"]},
        {"label": "فياريال", "aliases": ["villarreal"]},
        {"label": "وست هام", "aliases": ["west ham"]},
        {"label": "أستون فيلا", "aliases": ["aston villa"]},
        {"label": "إيفرتون", "aliases": ["everton"]},
        {"label": "ليدز يونايتد", "aliases": ["leeds united"]},
        {"label": "نوتنغهام فورست", "aliases": ["nottingham forest"]},
        {"label": "شالكه", "aliases": ["schalke"]},
        {"label": "هامبورغ", "aliases": ["hamburg"]},
        {"label": "شتوتغارت", "aliases": ["stuttgart"]},
        {"label": "فيورنتينا", "aliases": ["fiorentina"]},
        {"label": "بولونيا", "aliases": ["bologna"]},
        {"label": "سامبدوريا", "aliases": ["sampdoria"]},
        {"label": "تورينو", "aliases": ["torino"]},
        {"label": "يانغ بويز", "aliases": ["young boys"]},
        {"label": "أندرلخت", "aliases": ["anderlecht"]},
        {"label": "كلوب بروج", "aliases": ["club brugge"]},
        {"label": "سلافيا براغ", "aliases": ["slavia prague"]},
        {"label": "دينامو زغرب", "aliases": ["dinamo zagreb"]},
        {"label": "بارتيزان", "aliases": ["partizan"]},
        {"label": "أولمبياكوس", "aliases": ["olympiacos"]},
        {"label": "سبارتا براغ", "aliases": ["sparta prague"]},
    ],
    "vegetables_and_fruits": [
        {"label": "بطاطا", "aliases": ["potato"]},
        {"label": "بطاطس", "aliases": ["potatoes"]},
        {"label": "طماطم", "aliases": ["tomato"]},
        {"label": "خيار", "aliases": ["cucumber"]},
        {"label": "جزر", "aliases": ["carrot"]},
        {"label": "بصل", "aliases": ["onion"]},
        {"label": "ثوم", "aliases": ["garlic"]},
        {"label": "فلفل أخضر", "aliases": ["green pepper"]},
        {"label": "فلفل أحمر", "aliases": ["red pepper"]},
        {"label": "فلفل أصفر", "aliases": ["yellow pepper"]},
        {"label": "كوسا", "aliases": ["zucchini"]},
        {"label": "باذنجان", "aliases": ["eggplant"]},
        {"label": "ملفوف", "aliases": ["cabbage"]},
        {"label": "خس", "aliases": ["lettuce"]},
        {"label": "سبانخ", "aliases": ["spinach"]},
        {"label": "بروكلي", "aliases": ["broccoli"]},
        {"label": "قرنبيط", "aliases": ["cauliflower"]},
        {"label": "فاصوليا", "aliases": ["beans"]},
        {"label": "بازلاء", "aliases": ["peas"]},
        {"label": "ذرة", "aliases": ["corn"]},
        {"label": "فجل", "aliases": ["radish"]},
        {"label": "لفت", "aliases": ["turnip"]},
        {"label": "شمندر", "aliases": ["beetroot"]},
        {"label": "بقدونس", "aliases": ["parsley"]},
        {"label": "كزبرة", "aliases": ["coriander"]},
        {"label": "نعناع", "aliases": ["mint"]},
        {"label": "جرجير", "aliases": ["arugula"]},
        {"label": "فطر", "aliases": ["mushroom"]},
        {"label": "بطاطا حلوة", "aliases": ["sweet potato"]},
        {"label": "يقطين", "aliases": ["pumpkin"]},
        {"label": "عدس", "aliases": ["lentils"]},
        {"label": "حمص", "aliases": ["chickpeas"]},
        {"label": "فول", "aliases": ["fava beans"]},
        {"label": "زنجبيل", "aliases": ["ginger"]},
        {"label": "بصل", "aliases": ["white onion"]},
        {"label": "ملوخية", "aliases": ["molokhia"]},
        {"label": "فاصوليا خضراء", "aliases": ["green beans"]},
        {"label": "بازلاء خضراء", "aliases": ["green peas"]},
        {"label": "تفاح", "aliases": ["apple"]},
        {"label": "موز", "aliases": ["banana"]},
        {"label": "برتقال", "aliases": ["orange"]},
        {"label": "ليمون", "aliases": ["lemon"]},
        {"label": "فراولة", "aliases": ["strawberry"]},
        {"label": "عنب", "aliases": ["grapes"]},
        {"label": "بطيخ", "aliases": ["watermelon"]},
        {"label": "شمام", "aliases": ["melon"]},
        {"label": "أناناس", "aliases": ["pineapple"]},
        {"label": "مانجا", "aliases": ["mango"]},
        {"label": "كيوي", "aliases": ["kiwi"]},
        {"label": "خوخ", "aliases": ["peach"]},
        {"label": "مشمش", "aliases": ["apricot"]},
        {"label": "كرز", "aliases": ["cherry"]},
        {"label": "رمان", "aliases": ["pomegranate"]},
        {"label": "تين", "aliases": ["fig"]},
        {"label": "تمر", "aliases": ["dates"]},
        {"label": "جوافة", "aliases": ["guava"]},
        {"label": "يوسفي", "aliases": ["mandarin"]},
        {"label": "توت", "aliases": ["berries"]},
        {"label": "توت أسود", "aliases": ["blackberry"]},
        {"label": "جوز الهند", "aliases": ["coconut"]},
        {"label": "سفرجل", "aliases": ["quince"]},
        {"label": "جوز", "aliases": ["walnut"]},
        {"label": "لوز", "aliases": ["almond"]},
        {"label": "فستق", "aliases": ["pistachio"]},
        {"label": "بندق", "aliases": ["hazelnut"]},
        {"label": "زبيب", "aliases": ["raisins"]},
    ],
}