CATEGORIES = {
    "football_players": [
        {"label": "ليونيل ميسي", "aliases": ["ميسي", "ليونيل", "ليو ميسي", "messi", "lionel messi"]},
        {"label": "كريستيانو رونالدو", "aliases": ["رونالدو", "كريستيانو", "cristiano", "ronaldo", "cristiano ronaldo"]},
        {"label": "محمد صلاح", "aliases": ["صلاح", "محمد صلاح", "mohamed salah", "salah"]},
        {"label": "كيليان مبابي", "aliases": ["مبابي", "كيليان", "mbappe", "kylian mbappe"]},
        {"label": "نيمار", "aliases": ["نيمار", "neymar"]},
        {"label": "لوكا مودريتش", "aliases": ["مودريتش", "لوكا", "modric", "luka modric"]},
        {"label": "روبرت ليفاندوفسكي", "aliases": ["ليفاندوفسكي", "روبرت", "lewandowski", "robert lewandowski"]},
        {"label": "إيرلينغ هالاند", "aliases": ["هالاند", "إيرلينغ", "haaland", "erling haaland"]},
    ],
    "countries": [
        {"label": "سوريا", "aliases": ["سوريا", "syria"]},
        {"label": "ألمانيا", "aliases": ["المانيا", "ألمانيا", "germany"]},
        {"label": "فرنسا", "aliases": ["فرنسا", "france"]},
        {"label": "اليابان", "aliases": ["اليابان", "japan"]},
        {"label": "البرازيل", "aliases": ["البرازيل", "brazil"]},
        {"label": "الأرجنتين", "aliases": ["الارجنتين", "الأرجنتين", "argentina"]},
        {"label": "إيطاليا", "aliases": ["ايطاليا", "إيطاليا", "italy"]},
        {"label": "مصر", "aliases": ["مصر", "egypt"]},
    ],
    "animals": [
        {"label": "أسد", "aliases": ["اسد", "أسد", "lion"]},
        {"label": "نمر", "aliases": ["نمر", "tiger"]},
        {"label": "فيل", "aliases": ["فيل", "elephant"]},
        {"label": "قرد", "aliases": ["قرد", "monkey"]},
        {"label": "زرافة", "aliases": ["زرافه", "زرافة", "giraffe"]},
        {"label": "بطريق", "aliases": ["بطريق", "penguin"]},
        {"label": "دلفين", "aliases": ["دلفين", "dolphin"]},
        {"label": "ذئب", "aliases": ["ذيب", "ذئب", "wolf"]},
    ],
    "cartoon_characters": [
        {"label": "سبونج بوب", "aliases": ["سبونج بوب", "سبونج", "spongebob", "sponge bob"]},
        {"label": "توم", "aliases": ["توم", "tom"]},
        {"label": "جيري", "aliases": ["جيري", "jerry"]},
        {"label": "شريك", "aliases": ["شريك", "shrek"]},
        {"label": "سيمبا", "aliases": ["سيمبا", "simba"]},
        {"label": "ميكي ماوس", "aliases": ["ميكي", "ميكي ماوس", "mickey", "mickey mouse"]},
        {"label": "بطوط", "aliases": ["بطوط", "donald duck", "donald"]},
        {"label": "سكوبي دو", "aliases": ["سكوبي", "سكوبي دو", "scooby", "scooby doo"]},
    ],
    "historical_figures": [
        {"label": "صلاح الدين", "aliases": ["صلاح الدين", "صلاح دين", "saladin"]},
        {"label": "نابليون", "aliases": ["نابليون", "napoleon"]},
        {"label": "الإسكندر الأكبر", "aliases": ["الاسكندر الاكبر", "الإسكندر الأكبر", "الاسكندر", "alexander the great"]},
        {"label": "شكسبير", "aliases": ["شكسبير", "shakespeare"]},
        {"label": "أينشتاين", "aliases": ["اينشتاين", "أينشتاين", "einstein"]},
        {"label": "نيوتن", "aliases": ["نيوتن", "newton"]},
        {"label": "كليوباترا", "aliases": ["كليوباترا", "cleopatra"]},
        {"label": "جوليوس قيصر", "aliases": ["يوليوس قيصر", "جوليوس قيصر", "caesar", "julius caesar"]},
    ],
}