CATEGORIES = {
    "football_players": [
        {"label": "ليونيل ميسي", "aliases": ["ميسي", "ليونيل", "messi", "lionel messi"]},
        {"label": "كريستيانو رونالدو", "aliases": ["رونالدو", "كريستيانو", "cristiano", "ronaldo"]},
        {"label": "محمد صلاح", "aliases": ["صلاح", "mohamed salah", "salah"]},
        {"label": "كيليان مبابي", "aliases": ["مبابي", "mbappe", "kylian mbappe"]},
        {"label": "نيمار", "aliases": ["neymar"]},
        {"label": "لوكا مودريتش", "aliases": ["مودريتش", "modric"]},
        {"label": "روبرت ليفاندوفسكي", "aliases": ["ليفاندوفسكي", "lewandowski"]},
        {"label": "إيرلينغ هالاند", "aliases": ["هالاند", "haaland"]},
        {"label": "كريم بنزيما", "aliases": ["بنزيما", "benzema"]},
        {"label": "رونالدينيو", "aliases": ["ronaldinho"]},
        {"label": "زين الدين زيدان", "aliases": ["زيدان", "zidane"]},
        {"label": "تشافي", "aliases": ["xavi"]},
        {"label": "إنييستا", "aliases": ["iniesta"]},
        {"label": "سيرجيو راموس", "aliases": ["راموس", "ramos"]},
        {"label": "جيرارد بيكيه", "aliases": ["بيكيه", "pique"]},
        {"label": "لويس سواريز", "aliases": ["سواريز", "suarez"]},
        {"label": "سيرجيو أغويرو", "aliases": ["اغويرو", "aguero"]},
        {"label": "تييري هنري", "aliases": ["هنري", "henry"]},
        {"label": "ديفيد بيكهام", "aliases": ["بيكهام", "beckham"]},
        {"label": "واين روني", "aliases": ["روني", "rooney"]},
        {"label": "ستيفن جيرارد", "aliases": ["جيرارد", "gerrard"]},
        {"label": "فرانك لامبارد", "aliases": ["لامبارد", "lampard"]},
        {"label": "أندريا بيرلو", "aliases": ["بيرلو", "pirlo"]},
        {"label": "جيانلويجي بوفون", "aliases": ["بوفون", "buffon"]},
        {"label": "إيكر كاسياس", "aliases": ["كاسياس", "casillas"]},
        {"label": "مانويل نوير", "aliases": ["نوير", "neuer"]},
        {"label": "توني كروس", "aliases": ["كروس", "kroos"]},
        {"label": "توماس مولر", "aliases": ["مولر", "muller"]},
        {"label": "ماركو رويس", "aliases": ["رويس", "reus"]},
        {"label": "إيدين هازارد", "aliases": ["هازارد", "hazard"]},
        {"label": "كيفين دي بروين", "aliases": ["دي بروين", "de bruyne"]},
        {"label": "تيبو كورتوا", "aliases": ["كورتوا", "courtois"]},
        {"label": "هاري كين", "aliases": ["كين", "kane"]},
        {"label": "سون هيونغ مين", "aliases": ["سون", "son"]},
        {"label": "غاريث بيل", "aliases": ["بيل", "bale"]},
        {"label": "فرانك ريبيري", "aliases": ["ريبيري", "ribery"]},
        {"label": "آريين روبن", "aliases": ["روبن", "robben"]},
        {"label": "صامويل إيتو", "aliases": ["ايتو", "eto"]},
        {"label": "ديدييه دروغبا", "aliases": ["دروغبا", "drogba"]},
        {"label": "يايا توريه", "aliases": ["توريه", "yaya toure"]},
        {"label": "كاكا", "aliases": ["kaka"]},
        {"label": "ريفالدو", "aliases": ["rivaldo"]},
        {"label": "روماريو", "aliases": ["romario"]},
        {"label": "رونالدو نازاريو", "aliases": ["الظاهرة", "ronaldo"]},
        {"label": "دييغو مارادونا", "aliases": ["مارادونا", "maradona"]},
        {"label": "بيليه", "aliases": ["pele"]},
        {"label": "ميشيل بلاتيني", "aliases": ["بلاتيني", "platini"]},
        {"label": "روبرتو باجيو", "aliases": ["باجيو", "baggio"]},
        {"label": "أليساندرو ديل بييرو", "aliases": ["ديل بييرو", "del piero"]},
        {"label": "فرانشيسكو توتي", "aliases": ["توتي", "totti"]},
        {"label": "أليساندرو نيستا", "aliases": ["نيستا", "nesta"]},
        {"label": "باولو مالديني", "aliases": ["مالديني", "maldini"]},
        {"label": "فابيو كانافارو", "aliases": ["كانافارو", "cannavaro"]},
        {"label": "جورجيو كيليني", "aliases": ["كيليني", "chiellini"]},
        {"label": "ليوناردو بونوتشي", "aliases": ["بونوتشي", "bonucci"]},
        {"label": "داني ألفيس", "aliases": ["الفيس", "dani alves"]},
        {"label": "مارسيلو", "aliases": ["marcelo"]},
        {"label": "كافو", "aliases": ["cafu"]},
        {"label": "روبرتو كارلوس", "aliases": ["كارلوس", "roberto carlos"]},
        {"label": "ليليان تورام", "aliases": ["تورام", "thuram"]},
        {"label": "باتريك فييرا", "aliases": ["فييرا", "vieira"]},
        {"label": "كلود ماكيليلي", "aliases": ["ماكيليلي", "makelele"]},
        {"label": "مايكل إيسيان", "aliases": ["ايسيان", "essien"]},
        {"label": "باستيان شفاينشتايغر", "aliases": ["شفاينشتايغر", "schweinsteiger"]},
        {"label": "فيليب لام", "aliases": ["لام", "lahm"]},
        {"label": "مايكل بالاك", "aliases": ["بالاك", "ballack"]},
        {"label": "مسعود أوزيل", "aliases": ["اوزيل", "ozil"]},
        {"label": "أليكسيس سانشيز", "aliases": ["سانشيز", "sanchez"]},
        {"label": "أرتورو فيدال", "aliases": ["فيدال", "vidal"]},
        {"label": "إدينسون كافاني", "aliases": ["كافاني", "cavani"]},
        {"label": "دييغو فورلان", "aliases": ["فورلان", "forlan"]},
        {"label": "كارلوس فالديراما", "aliases": ["فالديراما", "valderrama"]},
        {"label": "خاميس رودريغيز", "aliases": ["خاميس", "james rodriguez"]},
        {"label": "راداميل فالكاو", "aliases": ["فالكاو", "falcao"]},
        {"label": "باولو ديبالا", "aliases": ["ديبالا", "dybala"]},
        {"label": "غونزالو هيغواين", "aliases": ["هيغواين", "higuain"]},
        {"label": "أنخيل دي ماريا", "aliases": ["دي ماريا", "di maria"]},
        {"label": "أنطوان غريزمان", "aliases": ["غريزمان", "griezmann"]},
        {"label": "جوشوا كيميتش", "aliases": ["كيميتش", "kimmich"]},
        {"label": "غافي", "aliases": ["gavi"]},
        {"label": "بيدري", "aliases": ["pedri"]},
        {"label": "جود بيلينغهام", "aliases": ["بيلينغهام", "bellingham"]},
        {"label": "فينيسيوس جونيور", "aliases": ["فينيسيوس", "vinicius"]},
        {"label": "رودريغو", "aliases": ["rodrygo"]},
        {"label": "برناردو سيلفا", "aliases": ["سيلفا", "bernardo"]},
        {"label": "روبن دياز", "aliases": ["دياز", "ruben dias"]},
        {"label": "كايل ووكر", "aliases": ["ووكر", "walker"]},
        {"label": "رحيم سترلينغ", "aliases": ["سترلينغ", "sterling"]},
        {"label": "رياض محرز", "aliases": ["محرز", "mahrez"]},
        {"label": "ساديو ماني", "aliases": ["ماني", "mane"]},
        {"label": "كاليدو كوليبالي", "aliases": ["كوليبالي", "koulibaly"]},
        {"label": "فيكتور أوسيمين", "aliases": ["اوسيمين", "osimhen"]},
        {"label": "أشرف حكيمي", "aliases": ["حكيمي", "hakimi"]},
        {"label": "حكيم زياش", "aliases": ["زياش", "ziyech"]},
        {"label": "كريستيان بوليسيتش", "aliases": ["بوليسيتش", "pulisic"]},
        {"label": "ألفونسو ديفيز", "aliases": ["ديفيز", "alphonso davies"]},
        {"label": "فيرجيل فان دايك", "aliases": ["فان دايك", "van dijk"]},
        {"label": "ترنت ألكسندر أرنولد", "aliases": ["ترنت", "arnold"]},
        {"label": "داروين نونيز", "aliases": ["نونيز", "nunez"]},
        {"label": "لاوتارو مارتينيز", "aliases": ["لاوتارو", "lautaro"]},
        {"label": "إنزو فيرنانديز", "aliases": ["إنزو", "enzo"]},
        {"label": "جوليان ألفاريز", "aliases": ["الفاريز", "alvarez"]},
        {"label": "أليكسيس ماك أليستر", "aliases": ["ماك اليستر", "mac allister"]},
    ],
    "countries": [
        {"label": "سوريا", "aliases": ["سوريا", "syria"]},
        {"label": "مصر", "aliases": ["مصر", "egypt"]},
        {"label": "السعودية", "aliases": ["السعودية", "saudi arabia"]},
        {"label": "الإمارات", "aliases": ["الامارات", "uae", "united arab emirates"]},
        {"label": "قطر", "aliases": ["qatar"]},
        {"label": "الكويت", "aliases": ["kuwait"]},
        {"label": "عمان", "aliases": ["oman"]},
        {"label": "اليمن", "aliases": ["yemen"]},
        {"label": "الأردن", "aliases": ["jordan"]},
        {"label": "لبنان", "aliases": ["lebanon"]},
        {"label": "فلسطين", "aliases": ["palestine"]},
        {"label": "العراق", "aliases": ["iraq"]},
        {"label": "المغرب", "aliases": ["morocco"]},
        {"label": "الجزائر", "aliases": ["algeria"]},
        {"label": "تونس", "aliases": ["tunisia"]},
        {"label": "ليبيا", "aliases": ["libya"]},
        {"label": "السودان", "aliases": ["sudan"]},
        {"label": "الصومال", "aliases": ["somalia"]},
        {"label": "جيبوتي", "aliases": ["djibouti"]},
        {"label": "موريتانيا", "aliases": ["mauritania"]},
        {"label": "جزر القمر", "aliases": ["comoros"]},
        {"label": "البحرين", "aliases": ["bahrain"]},
        {"label": "الولايات المتحدة", "aliases": ["امريكا", "usa", "united states"]},
        {"label": "بريطانيا", "aliases": ["uk", "england", "britain"]},
        {"label": "ألمانيا", "aliases": ["germany"]},
        {"label": "فرنسا", "aliases": ["france"]},
        {"label": "إيطاليا", "aliases": ["italy"]},
        {"label": "إسبانيا", "aliases": ["spain"]},
        {"label": "البرتغال", "aliases": ["portugal"]},
        {"label": "هولندا", "aliases": ["netherlands"]},
        {"label": "بلجيكا", "aliases": ["belgium"]},
        {"label": "سويسرا", "aliases": ["switzerland"]},
        {"label": "النمسا", "aliases": ["austria"]},
        {"label": "السويد", "aliases": ["sweden"]},
        {"label": "النرويج", "aliases": ["norway"]},
        {"label": "الدنمارك", "aliases": ["denmark"]},
        {"label": "فنلندا", "aliases": ["finland"]},
        {"label": "روسيا", "aliases": ["russia"]},
        {"label": "أوكرانيا", "aliases": ["ukraine"]},
        {"label": "بولندا", "aliases": ["poland"]},
        {"label": "رومانيا", "aliases": ["romania"]},
        {"label": "بلغاريا", "aliases": ["bulgaria"]},
        {"label": "اليونان", "aliases": ["greece"]},
        {"label": "تركيا", "aliases": ["turkey"]},
        {"label": "الصين", "aliases": ["china"]},
        {"label": "الهند", "aliases": ["india"]},
        {"label": "اليابان", "aliases": ["japan"]},
        {"label": "كوريا الجنوبية", "aliases": ["south korea"]},
        {"label": "كوريا الشمالية", "aliases": ["north korea"]},
        {"label": "إندونيسيا", "aliases": ["indonesia"]},
        {"label": "ماليزيا", "aliases": ["malaysia"]},
        {"label": "سنغافورة", "aliases": ["singapore"]},
        {"label": "تايلاند", "aliases": ["thailand"]},
        {"label": "فيتنام", "aliases": ["vietnam"]},
        {"label": "الفلبين", "aliases": ["philippines"]},
        {"label": "باكستان", "aliases": ["pakistan"]},
        {"label": "بنغلاديش", "aliases": ["bangladesh"]},
        {"label": "إيران", "aliases": ["iran"]},
        {"label": "كازاخستان", "aliases": ["kazakhstan"]},
        {"label": "أوزبكستان", "aliases": ["uzbekistan"]},
        {"label": "كندا", "aliases": ["canada"]},
        {"label": "المكسيك", "aliases": ["mexico"]},
        {"label": "البرازيل", "aliases": ["brazil"]},
        {"label": "الأرجنتين", "aliases": ["argentina"]},
        {"label": "تشيلي", "aliases": ["chile"]},
        {"label": "بيرو", "aliases": ["peru"]},
        {"label": "كولومبيا", "aliases": ["colombia"]},
        {"label": "فنزويلا", "aliases": ["venezuela"]},
        {"label": "أوروغواي", "aliases": ["uruguay"]},
        {"label": "باراغواي", "aliases": ["paraguay"]},
        {"label": "بوليفيا", "aliases": ["bolivia"]},
        {"label": "كوبا", "aliases": ["cuba"]},
        {"label": "بنما", "aliases": ["panama"]},
        {"label": "كوستاريكا", "aliases": ["costa rica"]},
        {"label": "غواتيمالا", "aliases": ["guatemala"]},
        {"label": "جنوب أفريقيا", "aliases": ["south africa"]},
        {"label": "نيجيريا", "aliases": ["nigeria"]},
        {"label": "كينيا", "aliases": ["kenya"]},
        {"label": "إثيوبيا", "aliases": ["ethiopia"]},
        {"label": "غانا", "aliases": ["ghana"]},
        {"label": "السنغال", "aliases": ["senegal"]},
        {"label": "الكاميرون", "aliases": ["cameroon"]},
        {"label": "ساحل العاج", "aliases": ["ivory coast"]},
        {"label": "أستراليا", "aliases": ["australia"]},
        {"label": "نيوزيلندا", "aliases": ["new zealand"]},
        {"label": "التشيك", "aliases": ["czech republic"]},
        {"label": "سلوفاكيا", "aliases": ["slovakia"]},
        {"label": "المجر", "aliases": ["hungary"]},
        {"label": "صربيا", "aliases": ["serbia"]},
        {"label": "كرواتيا", "aliases": ["croatia"]},
        {"label": "سلوفينيا", "aliases": ["slovenia"]},
        {"label": "البوسنة والهرسك", "aliases": ["bosnia"]},
        {"label": "ألبانيا", "aliases": ["albania"]},
        {"label": "مقدونيا الشمالية", "aliases": ["north macedonia"]},
        {"label": "مونتينيغرو", "aliases": ["montenegro"]},
        {"label": "أيرلندا", "aliases": ["ireland"]},
        {"label": "آيسلندا", "aliases": ["iceland"]},
    ],
    "animals": [
        {"label": "أسد", "aliases": ["اسد", "lion"]},
        {"label": "نمر", "aliases": ["tiger"]},
        {"label": "فهد", "aliases": ["cheetah"]},
        {"label": "فيل", "aliases": ["elephant"]},
        {"label": "زرافة", "aliases": ["giraffe"]},
        {"label": "قرد", "aliases": ["monkey"]},
        {"label": "شمبانزي", "aliases": ["chimpanzee"]},
        {"label": "غوريلا", "aliases": ["gorilla"]},
        {"label": "دب", "aliases": ["bear"]},
        {"label": "باندا", "aliases": ["panda"]},
        {"label": "ذئب", "aliases": ["wolf"]},
        {"label": "ثعلب", "aliases": ["fox"]},
        {"label": "كلب", "aliases": ["dog"]},
        {"label": "قط", "aliases": ["cat"]},
        {"label": "حصان", "aliases": ["horse"]},
        {"label": "حمار", "aliases": ["donkey"]},
        {"label": "بقرة", "aliases": ["cow"]},
        {"label": "ثور", "aliases": ["bull"]},
        {"label": "خروف", "aliases": ["sheep"]},
        {"label": "ماعز", "aliases": ["goat"]},
        {"label": "جمل", "aliases": ["camel"]},
        {"label": "غزال", "aliases": ["gazelle", "deer"]},
        {"label": "كنغر", "aliases": ["kangaroo"]},
        {"label": "كوالا", "aliases": ["koala"]},
        {"label": "تمساح", "aliases": ["crocodile"]},
        {"label": "سلحفاة", "aliases": ["turtle"]},
        {"label": "أفعى", "aliases": ["snake"]},
        {"label": "ضفدع", "aliases": ["frog"]},
        {"label": "قرش", "aliases": ["shark"]},
        {"label": "حوت", "aliases": ["whale"]},
        {"label": "دلفين", "aliases": ["dolphin"]},
        {"label": "أخطبوط", "aliases": ["octopus"]},
        {"label": "نسر", "aliases": ["eagle"]},
        {"label": "صقر", "aliases": ["falcon"]},
        {"label": "بومة", "aliases": ["owl"]},
        {"label": "غراب", "aliases": ["crow"]},
        {"label": "حمامة", "aliases": ["pigeon"]},
        {"label": "ببغاء", "aliases": ["parrot"]},
        {"label": "بط", "aliases": ["duck"]},
        {"label": "دجاج", "aliases": ["chicken"]},
        {"label": "ديك رومي", "aliases": ["turkey"]},
        {"label": "نعامة", "aliases": ["ostrich"]},
        {"label": "بطريق", "aliases": ["penguin"]},
        {"label": "خفاش", "aliases": ["bat"]},
        {"label": "قنفذ", "aliases": ["hedgehog"]},
        {"label": "سنجاب", "aliases": ["squirrel"]},
        {"label": "فأر", "aliases": ["mouse"]},
        {"label": "أرنب", "aliases": ["rabbit"]},
        {"label": "راكون", "aliases": ["raccoon"]},
        {"label": "ضبع", "aliases": ["hyena"]},
        {"label": "حمار وحشي", "aliases": ["zebra"]},
        {"label": "فرس النهر", "aliases": ["hippopotamus"]},
        {"label": "وحيد القرن", "aliases": ["rhinoceros"]},
        {"label": "نمر ثلجي", "aliases": ["snow leopard"]},
        {"label": "فهد أسود", "aliases": ["black panther"]},
        {"label": "بوما", "aliases": ["puma", "cougar"]},
        {"label": "بيسون", "aliases": ["bison"]},
        {"label": "دب قطبي", "aliases": ["polar bear"]},
        {"label": "نحلة", "aliases": ["bee"]},
        {"label": "فراشة", "aliases": ["butterfly"]},
    ],
    "cartoon_characters": [
        {"label": "شريك", "aliases": ["شريك", "shrek"]},
        {"label": "سيمبا", "aliases": ["سيمبا", "simba"]},
        {"label": "ميكي ماوس", "aliases": ["ميكي", "ميكي ماوس", "mickey", "mickey mouse"]},
        {"label": "بطوط", "aliases": ["بطوط", "donald duck", "donald"]},
        {"label": "سكوبي دو", "aliases": ["سكوبي", "سكوبي دو", "scooby", "scooby doo"]},
        {"label": "ناروتو", "aliases": ["naruto"]},
        {"label": "ساسكي", "aliases": ["sasuke"]},
        {"label": "غوكو", "aliases": ["goku"]},
        {"label": "فيجيتا", "aliases": ["vegeta"]},
        {"label": "كابتن ماجد", "aliases": ["tsubasa", "captain majed"]},
        {"label": "بسام", "aliases": ["bassam"]},
        {"label": "وليد", "aliases": ["waleed"]},
        {"label": "عدنان", "aliases": ["adnan"]},
        {"label": "لينا", "aliases": ["lina"]},
        {"label": "سالي", "aliases": ["sally"]},
        {"label": "ريمي", "aliases": ["remi"]},
        {"label": "ماوكلي", "aliases": ["mowgli"]},
        {"label": "سندباد", "aliases": ["sinbad"]},
        {"label": "توم", "aliases": ["tom"]},
        {"label": "جيري", "aliases": ["jerry"]},
        {"label": "سبونج بوب", "aliases": ["spongebob"]},
        {"label": "بسيط", "aliases": ["patrick"]},
        {"label": "ساندي", "aliases": ["sandy"]},
        {"label": "سكوبى دو", "aliases": ["scooby doo"]},
        {"label": "بن تن", "aliases": ["ben 10"]},
        {"label": "كونان", "aliases": ["conan"]},
        {"label": "بيكاتشو", "aliases": ["pikachu"]},
        {"label": "يوغي", "aliases": ["yugi"]},
        {"label": "ميكي ماوس", "aliases": ["mickey mouse"]},
        {"label": "بطوط", "aliases": ["donald duck"]},
        {"label": "تويتي", "aliases": ["tweety"]},
        {"label": "دورا", "aliases": ["dora"]},
        {"label": "دكستر", "aliases": ["dexter"]},
    ],
    "football_clubs": [
        {"label": "ريال مدريد", "aliases": ["real madrid"]},
        {"label": "برشلونة", "aliases": ["barcelona"]},
        {"label": "أتلتيكو مدريد", "aliases": ["atletico madrid"]},
        {"label": "مانشستر يونايتد", "aliases": ["manchester united"]},
        {"label": "مانشستر سيتي", "aliases": ["manchester city"]},
        {"label": "ليفربول", "aliases": ["liverpool"]},
        {"label": "تشيلسي", "aliases": ["chelsea"]},
        {"label": "أرسنال", "aliases": ["arsenal"]},
        {"label": "توتنهام", "aliases": ["tottenham"]},
        {"label": "نيوكاسل", "aliases": ["newcastle"]},
        {"label": "بايرن ميونخ", "aliases": ["bayern munich"]},
        {"label": "بوروسيا دورتموند", "aliases": ["dortmund"]},
        {"label": "لايبزيغ", "aliases": ["leipzig"]},
        {"label": "باير ليفركوزن", "aliases": ["leverkusen"]},
        {"label": "يوفنتوس", "aliases": ["juventus"]},
        {"label": "ميلان", "aliases": ["ac milan"]},
        {"label": "إنتر ميلان", "aliases": ["inter milan"]},
        {"label": "نابولي", "aliases": ["napoli"]},
        {"label": "روما", "aliases": ["roma"]},
        {"label": "لاتسيو", "aliases": ["lazio"]},
        {"label": "باريس سان جيرمان", "aliases": ["psg", "paris saint germain"]},
        {"label": "مارسيليا", "aliases": ["marseille"]},
        {"label": "ليون", "aliases": ["lyon"]},
        {"label": "موناكو", "aliases": ["monaco"]},
        {"label": "ليل", "aliases": ["lille"]},
        {"label": "أياكس", "aliases": ["ajax"]},
        {"label": "أيندهوفن", "aliases": ["psv"]},
        {"label": "فينورد", "aliases": ["feyenoord"]},
        {"label": "بنفيكا", "aliases": ["benfica"]},
        {"label": "بورتو", "aliases": ["porto"]},
        {"label": "سبورتينغ لشبونة", "aliases": ["sporting"]},
        {"label": "سلتيك", "aliases": ["celtic"]},
        {"label": "رينجرز", "aliases": ["rangers"]},
        {"label": "غلطة سراي", "aliases": ["galatasaray"]},
        {"label": "فنربخشة", "aliases": ["fenerbahce"]},
        {"label": "بشكتاش", "aliases": ["besiktas"]},
        {"label": "الهلال", "aliases": ["al hilal"]},
        {"label": "النصر", "aliases": ["al nassr"]},
        {"label": "الاتحاد", "aliases": ["al ittihad"]},
        {"label": "الأهلي", "aliases": ["al ahly"]},
        {"label": "الزمالك", "aliases": ["zamalek"]},
        {"label": "الوداد", "aliases": ["wydad"]},
        {"label": "الرجاء", "aliases": ["raja"]},
        {"label": "اتلتيك بلباو", "aliases": ["athletic bilbao"]},
        {"label": "ريال سوسيداد", "aliases": ["real sociedad"]},
        {"label": "فالنسيا", "aliases": ["valencia"]},
        {"label": "إشبيلية", "aliases": ["sevilla"]},
        {"label": "فياريال", "aliases": ["villarreal"]},
        {"label": "وست هام", "aliases": ["west ham"]},
        {"label": "أستون فيلا", "aliases": ["aston villa"]},
        {"label": "إيفرتون", "aliases": ["everton"]},
        {"label": "ليدز يونايتد", "aliases": ["leeds united"]},
        {"label": "نوتنغهام فورست", "aliases": ["nottingham forest"]},
        {"label": "شالكه", "aliases": ["schalke"]},
        {"label": "هامبورغ", "aliases": ["hamburg"]},
        {"label": "شتوتغارت", "aliases": ["stuttgart"]},
        {"label": "فيورنتينا", "aliases": ["fiorentina"]},
        {"label": "بولونيا", "aliases": ["bologna"]},
        {"label": "سامبدوريا", "aliases": ["sampdoria"]},
        {"label": "تورينو", "aliases": ["torino"]},
        {"label": "يانغ بويز", "aliases": ["young boys"]},
        {"label": "أندرلخت", "aliases": ["anderlecht"]},
        {"label": "كلوب بروج", "aliases": ["club brugge"]},
        {"label": "سلافيا براغ", "aliases": ["slavia prague"]},
        {"label": "دينامو زغرب", "aliases": ["dinamo zagreb"]},
        {"label": "بارتيزان", "aliases": ["partizan"]},
        {"label": "أولمبياكوس", "aliases": ["olympiacos"]},
        {"label": "سبارتا براغ", "aliases": ["sparta prague"]},
    ],
    "vegetables_and_fruits": [
        {"label": "بطاطا", "aliases": ["potato"]},
        {"label": "بطاطس", "aliases": ["potatoes"]},
        {"label": "طماطم", "aliases": ["tomato"]},
        {"label": "خيار", "aliases": ["cucumber"]},
        {"label": "جزر", "aliases": ["carrot"]},
        {"label": "بصل", "aliases": ["onion"]},
        {"label": "ثوم", "aliases": ["garlic"]},
        {"label": "فلفل أخضر", "aliases": ["green pepper"]},
        {"label": "فلفل أحمر", "aliases": ["red pepper"]},
        {"label": "فلفل أصفر", "aliases": ["yellow pepper"]},
        {"label": "كوسا", "aliases": ["zucchini"]},
        {"label": "باذنجان", "aliases": ["eggplant"]},
        {"label": "ملفوف", "aliases": ["cabbage"]},
        {"label": "خس", "aliases": ["lettuce"]},
        {"label": "سبانخ", "aliases": ["spinach"]},
        {"label": "بروكلي", "aliases": ["broccoli"]},
        {"label": "قرنبيط", "aliases": ["cauliflower"]},
        {"label": "فاصوليا", "aliases": ["beans"]},
        {"label": "بازلاء", "aliases": ["peas"]},
        {"label": "ذرة", "aliases": ["corn"]},
        {"label": "فجل", "aliases": ["radish"]},
        {"label": "لفت", "aliases": ["turnip"]},
        {"label": "شمندر", "aliases": ["beetroot"]},
        {"label": "بقدونس", "aliases": ["parsley"]},
        {"label": "كزبرة", "aliases": ["coriander"]},
        {"label": "نعناع", "aliases": ["mint"]},
        {"label": "جرجير", "aliases": ["arugula"]},
        {"label": "فطر", "aliases": ["mushroom"]},
        {"label": "بطاطا حلوة", "aliases": ["sweet potato"]},
        {"label": "يقطين", "aliases": ["pumpkin"]},
        {"label": "عدس", "aliases": ["lentils"]},
        {"label": "حمص", "aliases": ["chickpeas"]},
        {"label": "فول", "aliases": ["fava beans"]},
        {"label": "زنجبيل", "aliases": ["ginger"]},
        {"label": "بصل", "aliases": ["white onion"]},
        {"label": "ملوخية", "aliases": ["molokhia"]},
        {"label": "فاصوليا خضراء", "aliases": ["green beans"]},
        {"label": "بازلاء خضراء", "aliases": ["green peas"]},
        {"label": "تفاح", "aliases": ["apple"]},
        {"label": "موز", "aliases": ["banana"]},
        {"label": "برتقال", "aliases": ["orange"]},
        {"label": "ليمون", "aliases": ["lemon"]},
        {"label": "فراولة", "aliases": ["strawberry"]},
        {"label": "عنب", "aliases": ["grapes"]},
        {"label": "بطيخ", "aliases": ["watermelon"]},
        {"label": "شمام", "aliases": ["melon"]},
        {"label": "أناناس", "aliases": ["pineapple"]},
        {"label": "مانجا", "aliases": ["mango"]},
        {"label": "كيوي", "aliases": ["kiwi"]},
        {"label": "خوخ", "aliases": ["peach"]},
        {"label": "مشمش", "aliases": ["apricot"]},
        {"label": "كرز", "aliases": ["cherry"]},
        {"label": "رمان", "aliases": ["pomegranate"]},
        {"label": "تين", "aliases": ["fig"]},
        {"label": "تمر", "aliases": ["dates"]},
        {"label": "جوافة", "aliases": ["guava"]},
        {"label": "يوسفي", "aliases": ["mandarin"]},
        {"label": "توت", "aliases": ["berries"]},
        {"label": "توت أسود", "aliases": ["blackberry"]},
        {"label": "جوز الهند", "aliases": ["coconut"]},
        {"label": "سفرجل", "aliases": ["quince"]},
        {"label": "جوز", "aliases": ["walnut"]},
        {"label": "لوز", "aliases": ["almond"]},
        {"label": "فستق", "aliases": ["pistachio"]},
        {"label": "بندق", "aliases": ["hazelnut"]},
        {"label": "زبيب", "aliases": ["raisins"]},
    ],
    "cars": [
        {"label": "كيا", "aliases": ["kia"]},
        {"label": "فورد", "aliases": ["ford"]},
        {"label": "هوندا", "aliases": ["honda"]},
        {"label": "تويوتا", "aliases": ["toyota"]},
        {"label": "بي إم دبليو", "aliases": ["bmw"]},
        {"label": "مرسيدس", "aliases": ["mercedes"]},
        {"label": "نيسان", "aliases": ["nissan"]},
        {"label": "هيونداي", "aliases": ["hyundai"]},
        {"label": "مازدا", "aliases": ["mazda"]},
        {"label": "سوبارو", "aliases": ["subaru"]},
        {"label": "أودي", "aliases": ["audi"]},
        {"label": "لكزس", "aliases": ["lexus"]},
        {"label": "فولكس فاجن", "aliases": ["volkswagen"]},
        {"label": "لاند روفر", "aliases": ["land rover"]},
        {"label": "شيفروليه", "aliases": ["chevrolet"]},
        {"label": "تسلا", "aliases": ["tesla"]},
        {"label": "جيب", "aliases": ["jeep"]},
        {"label": "بورشه", "aliases": ["porsche"]},
        {"label": "فيراري", "aliases": ["ferrari"]},
        {"label": "بي واي دي", "aliases": ["byd"]},
        {"label": "رولز رويس", "aliases": ["rolls royce"]},
        {"label": "بنتلي", "aliases": ["bentley"]},
        {"label": "لامبورغيني", "aliases": ["lamborghini"]},
        {"label": "ماكلارين", "aliases": ["mclaren"]},
        {"label": "أستون مارتن", "aliases": ["aston martin"]},
        {"label": "فولفو", "aliases": ["volvo"]},
        {"label": "كاديلاك", "aliases": ["cadillac"]},
        {"label": "دودج", "aliases": ["dodge"]},
        {"label": "جيلي", "aliases": ["geely"]},
        {"label": "سوزوكي", "aliases": ["suzuki"]},
    ],
    "syrian_food": [
        {"label": "كبة", "aliases": ["kibbeh"]},
        {"label": "تبولة", "aliases": ["tabbouleh"]},
        {"label": "فتوش", "aliases": ["fattoush"]},
        {"label": "شاورما", "aliases": ["shawarma"]},
        {"label": "مجدرة", "aliases": ["mujaddara"]},
        {"label": "محمرة", "aliases": ["muhammara"]},
        {"label": "يالنجي", "aliases": ["yalangi"]},
        {"label": "شاكرية", "aliases": ["shakriya"]},
        {"label": "فتة", "aliases": ["fatteh"]},
        {"label": "ملوخية", "aliases": ["molokhia"]},
        {"label": "أوزي", "aliases": ["ouzi"]},
        {"label": "منسف", "aliases": ["mansaf"]},
        {"label": "حراق إصبعو", "aliases": ["harak osbao"]},
        {"label": "شيخ المحشي", "aliases": ["sheikh al-mahshi"]},
        {"label": "بابا غنوج", "aliases": ["baba ghanoush"]},
        {"label": "مسبحة", "aliases": ["msabbaha"]},
        {"label": "فول", "aliases": ["foul"]},
        {"label": "فلافل", "aliases": ["falafel"]},
        {"label": "تسقية", "aliases": ["tesqiya"]},
        {"label": "كبة لبنية", "aliases": ["kibbeh labanieh"]},
        {"label": "صفيحة", "aliases": ["sfiha"]},
        {"label": "برك", "aliases": ["borek"]},
        {"label": "مناقيش", "aliases": ["manakish"]},
        {"label": "كوسا محشي", "aliases": ["stuffed zucchini"]},
        {"label": "باشا وعساكره", "aliases": ["pasha wa asakiro"]},
        {"label": "مقلوبة", "aliases": ["maqluba"]},
        {"label": "فريكة", "aliases": ["freekeh"]},
        {"label": "مشاوي", "aliases": ["grill", "bbq"]},
        {"label": "شيش برك", "aliases": ["shish barak"]},
        {"label": "كبة مشوية", "aliases": ["grilled kibbeh"]},
        {"label": "كبة مقلية", "aliases": ["fried kibbeh"]},
        {"label": "كبة نية", "aliases": ["raw kibbeh"]},
        {"label": "كبة صاجية", "aliases": ["sajiyah kibbeh"]},
        {"label": "كبة حلبة", "aliases": ["aleppo kibbeh"]},
        {"label": "كبة مبرومة", "aliases": ["mabrouma kibbeh"]},
        {"label": "سفرجلية", "aliases": ["safarjaliya"]},
        {"label": "سماقية", "aliases": ["sumaqiya"]},
        {"label": "محاشي", "aliases": ["mahshi"]},
        {"label": "بامية", "aliases": ["bamia"]},
        {"label": "فاصولياء خضراء", "aliases": ["green beans"]},
        {"label": "بازيلاء ورز", "aliases": ["peas and rice"]},
        {"label": "يخنة بطاطا", "aliases": ["potato stew"]},
        {"label": "مليحي", "aliases": ["maleehi"]},
        {"label": "كبة سماقية", "aliases": ["sumaqiya kibbeh"]},
        {"label": "كباب هندي", "aliases": ["indian kebab"]},
        {"label": "داوود باشا", "aliases": ["dawood pasha"]},
        {"label": "مخلوطة", "aliases": ["makhlouta"]},
        {"label": "عدس بحامض", "aliases": ["lentils with lemon"]},
        {"label": "مجدرة رز", "aliases": ["rice mujaddara"]},
        {"label": "مجدرة برغل", "aliases": ["bulgur mujaddara"]},
        {"label": "أرمنية", "aliases": ["armaniya"]},
        {"label": "عجة سورية", "aliases": ["syrian ejjeh"]},
        {"label": "مكمورة", "aliases": ["makmoura"]},
        {"label": "منزلة بتنجان", "aliases": ["eggplant manzala"]},
        {"label": "مسقعة بتنجان", "aliases": ["eggplant moussaka"]},
        {"label": "صيادية سمك", "aliases": ["sayadieh"]},
        {"label": "حرايروز", "aliases": ["harayeroz"]},
        {"label": "جز مز", "aliases": ["jaz maz"]},
        {"label": "مطبق بتنجان", "aliases": ["mutabbaq eggplant"]},
        {"label": "شوربة عدس", "aliases": ["lentil soup"]},
        {"label": "تسقية بالسمنة", "aliases": ["fatteh with ghee"]},
        {"label": "تسقية بالزيت", "aliases": ["fatteh with oil"]},
        {"label": "لحم بعجين", "aliases": ["lahm bi ajin"]},
        {"label": "عرايس", "aliases": ["arayes"]},
        {"label": "شيش طاووق", "aliases": ["shish taouk"]},
        {"label": "متبل بتنجان", "aliases": ["mutabbal"]},
        {"label": "لبنية برز", "aliases": ["labniyeh with rice"]},
        {"label": "كبة بالصينية", "aliases": ["kibbeh bil saniyeh"]},
        {"label": "كبة مسموقة", "aliases": ["masmouka kibbeh"]},
        {"label": "رز بفول", "aliases": ["rice with fava beans"]}
    ],
    "syrian_series": [
        {"label": "مولانا", "aliases": ["mawlana", "تيم حسن 2026"]},
        {"label": "مطبخ المدينة", "aliases": ["city kitchen", "عباس النوري وأمل عرفة"]},
        {"label": "بخمس أرواح", "aliases": ["5 arwah", "قصي خولي وكاريس بشار"]},
        {"label": "سعادة المجنون", "aliases": ["saadat al majnoun", "عابد فهد وسلافة معمار"]},
        {"label": "الخروج من البئر", "aliases": ["exit from the well", "جمال سليمان"]},
        {"label": "عيلة الملك", "aliases": ["the king's family", "سلوم حداد وشكران مرتجى"]},
        {"label": "أنا وهي وهيا", "aliases": ["ana wa hiya wa haya", "أمل عرفة ونادين تحسين بيك"]},
        {"label": "المقعد الأخير", "aliases": ["the last seat", "دراما اجتماعية"]},
        {"label": "السوريون الأعداء", "aliases": ["the syrians enemies", "دراما تاريخية معاصرة"]},
        {"label": "النويلاتي", "aliases": ["al nowailati", "صراع الحرف"]},
        {"label": "لا مكان لا زمان", "aliases": ["no place no time", "سلسلة قيصر"]},
        {"label": "شمس الأصيل", "aliases": ["shams al aseel", "دانا جبر ووائل زيدان"]},
        {"label": "لوبي الغرام", "aliases": ["lobby al gharam", "كوميديا رومانسية"]},
        {"label": "اليتيم", "aliases": ["al yateem", "دراما إنسانية"]},
        {"label": "المليئية", "aliases": ["al maleeiya", "دراما ريفية"]},
        {"label": "باب الحارة", "aliases": ["bab al hara"]},
        {"label": "مرايا", "aliases": ["maraya"]},
        {"label": "بقعة ضوء", "aliases": ["buqat dawt"]},
        {"label": "ضيعة ضايعة", "aliases": ["dayaa dayaa"]},
        {"label": "الزير سالم", "aliases": ["al zeer salem"]},
        {"label": "الفصول الأربعة", "aliases": ["al fosoul al arbaa"]},
        {"label": "ليالي الصالحية", "aliases": ["layali al salhiya"]},
        {"label": "أهل الراية", "aliases": ["ahl al raya"]},
        {"label": "الخربة", "aliases": ["al khirba"]},
        {"label": "أيام شامية", "aliases": ["ayam shamiya"]},
        {"label": "تخت شرقي", "aliases": ["takht sharqi"]},
        {"label": "غزلان في غابة الذئاب", "aliases": ["ghizlan"]},
        {"label": "الانتظار", "aliases": ["al intizar"]},
        {"label": "نزار قباني", "aliases": ["nizar qabbani"]},
        {"label": "ولادة من الخاصرة", "aliases": ["wilada"]},
        {"label": "الندم", "aliases": ["al nadam"]},
        {"label": "كسر عضم", "aliases": ["kasr adhm"]},
        {"label": "العربجي", "aliases": ["al arbaji"]},
        {"label": "مال القبان", "aliases": ["mal al qabban"]},
        {"label": "على صفيح ساخن", "aliases": ["ala safih sakhin"]},
        {"label": "تاج", "aliases": ["taj"]},
        {"label": "زند", "aliases": ["zand"]},
        {"label": "أحلام كبيرة", "aliases": ["ahlam kabira"]},
        {"label": "عصي الدمع", "aliases": ["asi al damoo"]},
        {"label": "بكرا أحلى", "aliases": ["bukra ahla"]},
        {"label": "بطل من هذا الزمان", "aliases": ["batal"]},
        {"label": "جميل وهناء", "aliases": ["jamil wa hanaa"]},
        {"label": "يوميات مدير عام", "aliases": ["mudir aam"]},
        {"label": "عيلة خمس نجوم", "aliases": ["ayla 5 stars"]},
        {"label": "الخوالي", "aliases": ["al khawali"]},
        {"label": "التغريبة الفلسطينية", "aliases": ["al taghriba"]},
        {"label": "نهاية رجل شجاع", "aliases": ["nihayat rajol shojaa"]},
        {"label": "الجوارح", "aliases": ["al jawareh"]},
        {"label": "الكواسر", "aliases": ["al kawaser"]},
        {"label": "صقر قريش", "aliases": ["saqr quraish"]},
        {"label": "ربيع قرطبة", "aliases": ["rabee qortoba"]},
        {"label": "ملوك الطوائف", "aliases": ["molook al tawaef"]},
        {"label": "رسائل الحب والحرب", "aliases": ["rasael al hob"]},
        {"label": "ليس سرابا", "aliases": ["laysa saraban"]},
        {"label": "زمن العار", "aliases": ["zaman al aar"]},
        {"label": "قلم حمرة", "aliases": ["qalam homra"]},
        {"label": "أرواح عارية", "aliases": ["arwah areya"]},
        {"label": "العشق الإلهي", "aliases": ["al eshq al ilahi"]},
        {"label": "عيلة 7 نجوم", "aliases": ["ayla 7 stars"]},
        {"label": "عيلة 8 نجوم", "aliases": ["ayla 8 stars"]},
        {"label": "أبو الهنا", "aliases": ["abu al hana"]},
        {"label": "دنيا", "aliases": ["donia"]},
        {"label": "عودة غوار", "aliases": ["awdat ghawar"]},
        {"label": "الدوامة", "aliases": ["al dawama"]},
        {"label": "الحصرم الشامي", "aliases": ["al hasram al shami"]},
        {"label": "طالع الفضة", "aliases": ["talee al fedda"]},
        {"label": "أوركيديا", "aliases": ["orchidia"]},
        {"label": "دقيقة صمت", "aliases": ["daqiqat samt"]},
        {"label": "مع وقف التنفيذ", "aliases": ["maa waqf al tanfeez"]},
        {"label": "حارة القبة", "aliases": ["harat al qobba"]},
        {"label": "سوق الحرير", "aliases": ["souq al hareer"]},
        {"label": "مسافة أمان", "aliases": ["masafat aman"]},
        {"label": "بلا غمد", "aliases": ["bila ghimd"]},
        {"label": "قناديل العشاق", "aliases": ["qanadeel al oshaq"]},
        {"label": "الشمس تشرق من جديد", "aliases": ["al shams"]},
        {"label": "الظاهر بيبرس", "aliases": ["baibars"]},
        {"label": "صلاح الدين الأيوبي", "aliases": ["salah al deen"]},
        {"label": "تغريبة بني هلال", "aliases": ["bani helal"]},
        {"label": "غدا نلتقي", "aliases": ["ghadan naltaqi"]},
        {"label": "سنعود بعد قليل", "aliases": ["sanaood"]},
        {"label": "الولادة من الخاصرة 2", "aliases": ["wilada 2"]},
        {"label": "الولادة من الخاصرة 3", "aliases": ["wilada 3"]},
        {"label": "حمام القيشاني", "aliases": ["hamam al qishani"]},
        {"label": "الجوكر", "aliases": ["al joker"]},
        {"label": "كسر عضم 2", "aliases": ["kasr adhm 2"]}
    ],
    "prophets": [
        {"label": "آدم", "aliases": ["adam"]},
        {"label": "إدريس", "aliases": ["idris"]},
        {"label": "نوح", "aliases": ["noah"]},
        {"label": "هود", "aliases": ["hud"]},
        {"label": "صالح", "aliases": ["saleh"]},
        {"label": "لوط", "aliases": ["lot"]},
        {"label": "إبراهيم", "aliases": ["abraham"]},
        {"label": "إسماعيل", "aliases": ["ishmael"]},
        {"label": "إسحاق", "aliases": ["isaac"]},
        {"label": "يعقوب", "aliases": ["jacob"]},
        {"label": "يوسف", "aliases": ["joseph"]},
        {"label": "أيوب", "aliases": ["job"]},
        {"label": "شعيب", "aliases": ["shuaib"]},
        {"label": "موسى", "aliases": ["moses"]},
        {"label": "هارون", "aliases": ["aaron"]},
        {"label": "ذو الكفل", "aliases": ["dhu al-kifl"]},
        {"label": "داوود", "aliases": ["david"]},
        {"label": "سليمان", "aliases": ["solomon"]},
        {"label": "إلياس", "aliases": ["elijah"]},
        {"label": "اليسع", "aliases": ["elisha"]},
        {"label": "يونس", "aliases": ["jonah"]},
        {"label": "زكريا", "aliases": ["zechariah"]},
        {"label": "يحيى", "aliases": ["john"]},
        {"label": "عيسى", "aliases": ["jesus"]},
        {"label": "محمد", "aliases": ["muhammad"]}
    ],
    "syrian_characters": [
        {"label": "أبو عصام", "aliases": ["abu issam", "شو كاين؟", "حكيم الحارة"]},
        {"label": "أبو غالب", "aliases": ["abu ghalib", "بليلة بلبلوكي"]},
        {"label": "النمس", "aliases": ["al nims", "يا ناموس", "يا حيوان"]},
        {"label": "معتز", "aliases": ["moataz", "العكيد معتز", "أبو العز"]},
        {"label": "أبو حاتم", "aliases": ["abu hatem", "أديب الحارة"]},
        {"label": "جودة أبو خميس", "aliases": ["jouda", "يا ولفي", "يا باطل"]},
        {"label": "أسعد خرشوف", "aliases": ["asaad", "يا ضنايا", "شحاطة"]},
        {"label": "سلنغو", "aliases": ["slango", "سليمان غانم"]},
        {"label": "عفوفة", "aliases": ["afoufa", "عفاف"]},
        {"label": "أبو شملة", "aliases": ["abu shamla", "يا دريبي"]},
        {"label": "أبو ليلى", "aliases": ["abu layla", "عنتر بن شداد"]},
        {"label": "مكسيموس", "aliases": ["maximus", "قصي خولي"]},
        {"label": "أبو كاسم", "aliases": ["abu kassem", "خياط الحارة"]},
        {"label": "نضال", "aliases": ["nidal", "الندم"]},
        {"label": "صخر شيخ الجبل", "aliases": ["sakhr", "صخر"]},
        {"label": "جبل شيخ الجبل", "aliases": ["jabal", "لا تهكلي الهم", "منتهية"]},
        {"label": "شاهين", "aliases": ["shahin", "شاهين شيخ الجبل"]},
        {"label": "مختار الميماس", "aliases": ["al mukhtar", "باسم ياخور"]},
        {"label": "أبو نيبال", "aliases": ["abu nibal", "هب الرعد"]},
        {"label": "رؤوف", "aliases": ["raouf", "المقدم رؤوف"]},
        {"label": "الخياط", "aliases": ["al khayat", "تيم حسن"]},
        {"label": "جميل", "aliases": ["jamil", "جميل السعيد"]},
        {"label": "هناء", "aliases": ["hana", "هناء الفودكة"]},
        {"label": "أمل", "aliases": ["amal", "أمل عرفة"]},
        {"label": "فوزية", "aliases": ["fawzia", "أم بدر"]},
        {"label": "سعاد", "aliases": ["souad", "أم عصام"]},
        {"label": "أبو بدر", "aliases": ["abu badr", "حيوان بالخمسة"]},
        {"label": "أبو جانتي", "aliases": ["abu janti", "ملك اللانسر"]},
        {"label": "خالد بن الوليد", "aliases": ["khaled", "سيف الله"]},
        {"label": "الزير سالم", "aliases": ["zeer salem", "عدي بن ربيعة"]},
        {"label": "كليب", "aliases": ["kuleib", "لا تصالح"]},
        {"label": "جسّاس", "aliases": ["jassas", "عابد فهد"]},
        {"label": "غوار الطوشة", "aliases": ["ghawar", "دريد لحام"]},
        {"label": "حسني البورظان", "aliases": ["hosni", "نهاد قلعي"]},
        {"label": "أبو عنتر", "aliases": ["abu antar", "ناجي جبر"]},
        {"label": "ياسينو", "aliases": ["yasino", "ياسين بقوش"]},
        {"label": "بهلول", "aliases": ["bahloul", "بهلول أعقل المجانين"]},
        {"label": "نضال بقعة ضوء", "aliases": ["nidal", "شخصيات متنوعة"]},
        {"label": "عصام", "aliases": ["issam", "ابن أبو عصام"]},
        {"label": "ديبة", "aliases": ["deeba", "تولاي هارون"]},
        {"label": "سعدو", "aliases": ["saado", "سعدو بباب الحارة"]},
        {"label": "الأدعشري", "aliases": ["al adashari", "بسّام كوسا"]},
        {"label": "المخرز", "aliases": ["al mokhriz", "ليالي الصالحية"]},
        {"label": "نصار ابن عريبي", "aliases": ["nassar", "الخوالي"]},
        {"label": "فطوم حيص بيص", "aliases": ["fattoum", "نجاح حفيظ"]},
        {"label": "أبو صياح", "aliases": ["abu sayyah", "رفيق سبيعي"]},
        {"label": "بوران", "aliases": ["bouran", "بنت أبو عصام"]},
        {"label": "لطفية", "aliases": ["loutfia", "مرت عصام"]},
        {"label": "عزو", "aliases": ["azzo", "ابن أبو كاسم"]},
        {"label": "الواوي", "aliases": ["al wawi", "مصطفى الخاني"]}
    ],
    "quran_references": [
        {"label": "سورة الفاتحة", "aliases": ["al-fatiha", "السبع المثاني", "أم الكتاب"]},
        {"label": "سورة البقرة", "aliases": ["al-baqarah", "سنام القرآن"]},
        {"label": "سورة الكهف", "aliases": ["al-kahf", "نور بين الجمعتين"]},
        {"label": "سورة يس", "aliases": ["yasin", "قلب القرآن"]},
        {"label": "سورة الملك", "aliases": ["al-mulk", "المنجية", "تبارك"]},
        {"label": "سورة الرحمن", "aliases": ["ar-rahman", "عروس القرآن"]},
        {"label": "سورة الواقعة", "aliases": ["al-waqia", "سورة الغنى"]},
        {"label": "سورة الإخلاص", "aliases": ["al-ikhlas", "قل هو الله أحد"]},
        {"label": "سورة الفلق", "aliases": ["al-falaq", "المعوذة الأولى"]},
        {"label": "سورة الناس", "aliases": ["an-nas", "المعوذة الثانية"]},
        {"label": "آية الكرسي", "aliases": ["ayat al-kursi", "أعظم آية في القرآن"]},
        {"label": "آمن الرسول", "aliases": ["aman al-rasul", "خواتيم البقرة"]},
        {"label": "خواتيم سورة الحشر", "aliases": ["hashr", "لو أنزلنا هذا القرآن"]},
        {"label": "سورة يوسف", "aliases": ["yusuf", "أحسن القصص"]},
        {"label": "سورة مريم", "aliases": ["maryam", "سورة مريم"]},
        {"label": "سورة طه", "aliases": ["taha", "طه"]},
        {"label": "سورة النور", "aliases": ["an-nur", "آية النور"]},
        {"label": "سورة القصص", "aliases": ["al-qasas", "قصص الأنبياء"]},
        {"label": "سورة الفتح", "aliases": ["al-fath", "إنا فتحنا لك فتحا مبينا"]},
        {"label": "سورة الحجرات", "aliases": ["al-hujurat", "سورة الأخلاق"]},
        {"label": "سورة ق", "aliases": ["qaf", "سورة ق"]},
        {"label": "سورة النجم", "aliases": ["an-najm", "والنجم إذا هوى"]},
        {"label": "سورة القمر", "aliases": ["al-qamar", "اقتربت الساعة"]},
        {"label": "سورة الحديد", "aliases": ["al-hadid", "سبح لله"]},
        {"label": "سورة الحشر", "aliases": ["al-hashr", "سورة الحشر"]},
        {"label": "سورة الممتحنة", "aliases": ["al-mumtahina", "الممتحنة"]},
        {"label": "سورة الصف", "aliases": ["as-saff", "سورة الصف"]},
        {"label": "سورة الجمعة", "aliases": ["al-jumu'ah", "صلاة الجمعة"]},
        {"label": "سورة المنافقون", "aliases": ["al-munafiqun", "المنافقون"]},
        {"label": "سورة التغابن", "aliases": ["at-taghabun", "يوم التغابن"]},
        {"label": "سورة الطلاق", "aliases": ["at-talaq", "سورة النساء الصغرى"]},
        {"label": "سورة التحريم", "aliases": ["at-tahrim", "يا أيها النبي"]},
        {"label": "سورة الضحى", "aliases": ["ad-duha", "والضحى"]},
        {"label": "سورة الشرح", "aliases": ["ash-sharh", "ألم نشرح لك صدرك"]},
        {"label": "سورة التين", "aliases": ["at-tin", "والتين والزيتون"]},
        {"label": "سورة العلق", "aliases": ["al-alaq", "اقرأ باسم ربك"]},
        {"label": "سورة القدر", "aliases": ["al-qadr", "ليلة القدر"]},
        {"label": "سورة الزلزلة", "aliases": ["az-zalzalah", "إذا زلزلت الأرض"]},
        {"label": "سورة العاديات", "aliases": ["al-adiyat", "والعاديات ضبحا"]},
        {"label": "سورة القارعة", "aliases": ["al-qari'ah", "يوم يكون الناس كالفراش"]},
        {"label": "سورة النبأ", "aliases": ["an-naba", "عم يتساءلون"]},
        {"label": "سورة النازعات", "aliases": ["an-nazi'at", "والنازعات غرقا"]},
        {"label": "سورة عبس", "aliases": ["abasa", "عبس وتولى"]},
        {"label": "سورة التكوير", "aliases": ["at-takwir", "إذا الشمس كورت"]},
        {"label": "سورة الانفطار", "aliases": ["al-infitar", "إذا السماء انفطرت"]},
        {"label": "سورة المطففين", "aliases": ["al-mutaffifin", "ويل للمطففين"]},
        {"label": "سورة الانشقاق", "aliases": ["al-inshiqaq", "إذا السماء انشقت"]},
        {"label": "سورة البروج", "aliases": ["al-buruj", "والسماء ذات البروج"]},
        {"label": "سورة الطارق", "aliases": ["at-tariq", "والسماء والطارق"]},
        {"label": "سورة الأعلى", "aliases": ["al-a'la", "سبح اسم ربك الأعلى"]}
    ],
    "video_games": [
        {"label": "ببجي", "aliases": ["pubg", "ببجي موبايل"]},
        {"label": "فورتنايت", "aliases": ["fortnite", "فورت نايت"]},
        {"label": "كول اوف ديوتي", "aliases": ["cod", "warzone", "كود"]},
        {"label": "ماين كرافت", "aliases": ["minecraft", "ماين كرافت"]},
        {"label": "جي تي أي", "aliases": ["gta", "grand theft auto", "قراند"]},
        {"label": "فيفا", "aliases": ["fifa", "fc 24", "fc 25", "اف سي"]},
        {"label": "روبلوكس", "aliases": ["roblox", "روبلوكس"]},
        {"label": "كاونتر سترايك", "aliases": ["csgo", "counter strike", "كاونتر"]},
        {"label": "ليج اوف ليجيندز", "aliases": ["lol", "league of legends", "ليج"]},
        {"label": "فالورانت", "aliases": ["valorant", "فالورانت"]},
        {"label": "أوفر واتش", "aliases": ["overwatch", "اوفر واتش"]},
        {"label": "روكيت ليج", "aliases": ["rocket league", "روكيت ليج"]},
        {"label": "إيلدن رينج", "aliases": ["elden ring", "ايلدن رينج"]},
        {"label": "ذا لاست اوف أس", "aliases": ["the last of us", "tlou", "ذا لاست"]},
        {"label": "غود أوف وار", "aliases": ["god of war", "gow", "كريتوس"]},
        {"label": "ريد ديد", "aliases": ["red dead redemption", "rdr2", "ريد ديد"]},
        {"label": "سبايدر مان", "aliases": ["spider-man", "سبايدر مان"]},
        {"label": "أساسنز كريد", "aliases": ["assassin's creed", "أساسن"]},
        {"label": "سايبر بانك", "aliases": ["cyberpunk 2077", "سايبر بانك"]},
        {"label": "ريزدنت إيفل", "aliases": ["resident evil", "re4", "ريزدنت"]},
        {"label": "تومب ريدر", "aliases": ["tomb raider", "لارا كروفت"]},
        {"label": "أنشارتد", "aliases": ["uncharted", "نثان دريك"]},
        {"label": "ويتشر", "aliases": ["the witcher", "جرالت"]},
        {"label": "أمانج أس", "aliases": ["among us", "امونج اس"]},
        {"label": "فول جايز", "aliases": ["fall guys", "فول جايز"]},
        {"label": "ليتل نايتميرز", "aliases": ["little nightmares", "ليتل نايتميرز"]},
        {"label": "ستريت فايتر", "aliases": ["street fighter", "ستريت فايتر"]},
        {"label": "تيكن", "aliases": ["tekken", "تيكن"]},
        {"label": "مورتال كومبات", "aliases": ["mortal kombat", "مورتال"]},
        {"label": "كراش", "aliases": ["crash bandicoot", "كراش"]},
        {"label": "سوبر ماريو", "aliases": ["super mario", "ماريو"]},
        {"label": "زيلدا", "aliases": ["zelda", "link"]},
        {"label": "باكمان", "aliases": ["pac-man", "باكمان"]},
        {"label": "سونيك", "aliases": ["sonic", "القنفذ سونيك"]},
        {"label": "بوكيمون", "aliases": ["pokemon", "بوكيمون"]},
        {"label": "سيمز", "aliases": ["the sims", "سيمز"]},
        {"label": "دووم", "aliases": ["doom", "دووم"]},
        {"label": "ليفت فور ديد", "aliases": ["left 4 dead", "ليفت فور ديد"]},
        {"label": "دوتا 2", "aliases": ["dota 2", "دوتا"]},
        {"label": "جينشين إمباكت", "aliases": ["genshin impact", "جينشين"]},
        {"label": "هيلو", "aliases": ["halo", "ماستر شيف"]},
        {"label": "هورايزن", "aliases": ["horizon zero dawn", "ألوي"]},
        {"label": "بلاد بورن", "aliases": ["bloodborne", "بلاد بورن"]},
        {"label": "سيكيرو", "aliases": ["sekiro", "سيكيرو"]},
        {"label": "سايلنت هيل", "aliases": ["silent hill", "سايلنت هيل"]},
        {"label": "تتريس", "aliases": ["tetris", "تتريس"]},
        {"label": "نيد فور سبيد", "aliases": ["need for speed", "nfs"]},
        {"label": "باتلفيلد", "aliases": ["battlefield", "باتلفيلد"]},
        {"label": "أبيكس ليجندز", "aliases": ["apex legends", "أبيكس"]},
        {"label": "بلاك ميث: ووكونغ", "aliases": ["black myth wukong", "ووكونغ"]},
        {"label": "ستارديو فالي", "aliases": ["stardew valley"]},
        {"label": "تيراريا", "aliases": ["terraria"]},
        {"label": "سكايرم", "aliases": ["skyrim", "the elder scrolls"]},
        {"label": "فال آوت", "aliases": ["fallout"]},
        {"label": "دارك سولز", "aliases": ["dark souls"]},
        {"label": "هولو نايت", "aliases": ["hollow knight"]},
        {"label": "كاب هيد", "aliases": ["cuphead"]},
        {"label": "راتشيت أند كلانك", "aliases": ["ratchet and clank"]},
        {"label": "جراند توريزمو", "aliases": ["gran turismo"]},
        {"label": "تويستد ميتال", "aliases": ["twisted metal"]},
        {"label": "ميتال جير", "aliases": ["metal gear solid", "سنيك"]},
        {"label": "كيندوم هارتس", "aliases": ["kingdom hearts"]},
        {"label": "فاينل فانتسي", "aliases": ["final fantasy"]},
        {"label": "بريسون آركيتكت", "aliases": ["prison architect"]},
        {"label": "يوروتراك", "aliases": ["euro truck simulator"]},
        {"label": "فلايت سيمولايتر", "aliases": ["microsoft flight simulator"]},
        {"label": "كلاش اوف كلانس", "aliases": ["clash of clans", "كلاش"]},
        {"label": "كلاش رويال", "aliases": ["clash royale"]},
        {"label": "سابوي", "aliases": ["subway surfers", "سابوي"]},
        {"label": "كاندي كراش", "aliases": ["candy crush"]},
        {"label": "انجري بيردز", "aliases": ["angry birds"]},
        {"label": "بلانتس فيرسز زومبيز", "aliases": ["pvz", "plants vs zombies"]},
        {"label": "ديترويت: بيكم هيومن", "aliases": ["detroit become human"]},
        {"label": "رينبو سيكس سيج", "aliases": ["rainbow six siege", "رينبو"]},
        {"label": "بايو شوك", "aliases": ["bioshock"]},
        {"label": "ماس إيفيكت", "aliases": ["mass effect"]},
        {"label": "دراغون إيدج", "aliases": ["dragon age"]},
        {"label": "هيل دايفرز 2", "aliases": ["helldivers 2"]},
        {"label": "بالدوز جيت 3", "aliases": ["baldurs gate 3"]},
        {"label": "ليثال كومباني", "aliases": ["lethal company"]}
    ],
    "superheroes": [
        {"label": "سبايدر مان", "aliases": ["spider-man", "peter parker", "الرجل العنكبوت"]},
        {"label": "ايرون مان", "aliases": ["iron man", "tony stark", "الرجل الحديدي"]},
        {"label": "كابتن أمريكا", "aliases": ["captain america", "steve rogers"]},
        {"label": "ثور", "aliases": ["thor", "god of thunder"]},
        {"label": "هالك", "aliases": ["hulk", "bruce banner", "العملاق الأخضر"]},
        {"label": "بلاك ويدو", "aliases": ["black widow", "natasha romanoff", "الأرملة السوداء"]},
        {"label": "دكتور سترينج", "aliases": ["doctor strange", "stephen strange"]},
        {"label": "بلاك بانثر", "aliases": ["black panther", "t'challa", "النمر الأسود"]},
        {"label": "وولفرين", "aliases": ["wolverine", "logan", "الرجل الذئب"]},
        {"label": "ديدبول", "aliases": ["deadpool", "wade wilson"]},
        {"label": "سوبرمان", "aliases": ["superman", "clark kent", "رجل الصلب"]},
        {"label": "باتمان", "aliases": ["batman", "bruce wayne", "الرجل الوطواط"]},
        {"label": "وندر وومان", "aliases": ["wonder woman", "diana prince", "المرأة المعجزة"]},
        {"label": "ذا فلاش", "aliases": ["the flash", "barry allen", "البرق"]},
        {"label": "أكوامان", "aliases": ["aquaman", "arthur curry"]},
        {"label": "جرين لانترن", "aliases": ["green lantern", "hal jordan", "الفانوس الأخضر"]},
        {"label": "جوكر", "aliases": ["joker", "the clown prince of crime"]},
        {"label": "هارلي كوين", "aliases": ["harley quinn", "dr. harleen quinzel"]},
        {"label": "سايبورغ", "aliases": ["cyborg", "victor stone"]},
        {"label": "شازام", "aliases": ["shazam", "billy batson"]},
        {"label": "نايت وينج", "aliases": ["nightwing", "dick grayson"]},
        {"label": "روبن", "aliases": ["robin", "damian wayne"]},
        {"label": "كات وومان", "aliases": ["catwoman", "selina kyle", "المرأة القطة"]},
        {"label": "فينوم", "aliases": ["venom", "eddie brock"]},
        {"label": "ثانوس", "aliases": ["thanos", "the mad titan"]},
        {"label": "لوكي", "aliases": ["loki", "god of mischief"]},
        {"label": "سكارليت ويتش", "aliases": ["scarlet witch", "wanda maximoff"]},
        {"label": "فيجن", "aliases": ["vision", "the vision"]},
        {"label": "آنت مان", "aliases": ["ant-man", "scott lang", "الرجل النملة"]},
        {"label": "ستار لورد", "aliases": ["star-lord", "peter quill"]},
        {"label": "غروت", "aliases": ["groot", "i am groot"]},
        {"label": "روكيت راكون", "aliases": ["rocket raccoon", "rocket"]},
        {"label": "دارك سايد", "aliases": ["darkseid", "uxas"]},
        {"label": "ليكس لوثر", "aliases": ["lex luthor", "lex"]},
        {"label": "بين", "aliases": ["bane", "the man who broke the bat"]},
        {"label": "بلاك آدم", "aliases": ["black adam", "teth-adam"]},
        {"label": "مون نايت", "aliases": ["moon knight", "marc spector", "فارس الليل"]},
        {"label": "ديرديفيل", "aliases": ["daredevil", "matt murdock", "الرجل الذي لا يخاف"]},
        {"label": "بونيشر", "aliases": ["punisher", "frank castle", "المعاقب"]},
        {"label": "جوست رايدر", "aliases": ["ghost rider", "johnny blaze", "السائق الشبح"]},
        {"label": "كابتن مارفل", "aliases": ["captain marvel", "carol danvers"]},
        {"label": "سيلفر سيرفر", "aliases": ["silver surfer", "norrin radd"]},
        {"label": "بروفيسور إكس", "aliases": ["professor x", "charles xavier"]},
        {"label": "ماغنيتو", "aliases": ["magneto", "erik lehnsherr"]},
        {"label": "ستورم", "aliases": ["storm", "oro munroe"]},
        {"label": "جين جراي", "aliases": ["jean grey", "phoenix"]},
        {"label": "رايفن", "aliases": ["raven", "rachel roth"]},
        {"label": "بيست بوي", "aliases": ["beast boy", "garfield logan"]},
        {"label": "مارشيان مان هانتر", "aliases": ["martian manhunter", "j'onn j'onzz"]},
        {"label": "جرين أرو", "aliases": ["green arrow", "oliver queen", "السهم الأخضر"]}
    ],
    "clothing_brands": [
        {"label": "نايكي", "aliases": ["nike"]},
        {"label": "أديداس", "aliases": ["adidas"]},
        {"label": "زارا", "aliases": ["zara"]},
        {"label": "غوتشي", "aliases": ["gucci"]},
        {"label": "لويس فيتون", "aliases": ["louis vuitton", "lv"]},
        {"label": "شانيل", "aliases": ["chanel"]},
        {"label": "إتش آند إم", "aliases": ["h&m"]},
        {"label": "بوما", "aliases": ["puma"]},
        {"label": "برادا", "aliases": ["prada"]},
        {"label": "ديور", "aliases": ["dior"]},
        {"label": "بالنسياغا", "aliases": ["balenciaga"]},
        {"label": "فرزاتشي", "aliases": ["versace"]},
        {"label": "نايك أير جوردان", "aliases": ["jordan", "air jordan"]},
        {"label": "تومي هيلفيغر", "aliases": ["tommy hilfiger"]},
        {"label": "رالف لورين", "aliases": ["ralph lauren", "polo"]},
        {"label": "كالفين كلاين", "aliases": ["calvin klein", "ck"]},
        {"label": "أرماني", "aliases": ["armani", "giorgio armani"]},
        {"label": "لاكوست", "aliases": ["lacoste", "التمساح"]},
        {"label": "ليفايز", "aliases": ["levi's", "levis"]},
        {"label": "ديزل", "aliases": ["diesel"]},
        {"label": "أوف وايت", "aliases": ["off-white"]},
        {"label": "فندي", "aliases": ["fendi"]},
        {"label": "هيرميس", "aliases": ["hermes"]},
        {"label": "باربري", "aliases": ["burberry"]},
        {"label": "دولتشي آند غابانا", "aliases": ["dolce & gabbana", "d&g"]},
        {"label": "فيكتوريا سيكريت", "aliases": ["victoria's secret"]},
        {"label": "غاب", "aliases": ["gap"]},
        {"label": "نيكست", "aliases": ["next"]},
        {"label": "بيرشكا", "aliases": ["bershka"]},
        {"label": "بول آند بير", "aliases": ["pull & bear"]},
        {"label": "ماسيمو دوتي", "aliases": ["massimo dutti"]},
        {"label": "مانغو", "aliases": ["mango"]},
        {"label": "ريبوك", "aliases": ["reebok"]},
        {"label": "أندر آرمور", "aliases": ["under armour"]},
        {"label": "نيو بالانس", "aliases": ["new balance", "nb"]},
        {"label": "نورث فيس", "aliases": ["the north face"]},
        {"label": "تيمبرلاند", "aliases": ["timberland"]},
        {"label": "كولومبيا", "aliases": ["columbia"]},
        {"label": "فانس", "aliases": ["vans"]},
        {"label": "كونفرس", "aliases": ["converse", "all star"]},
        {"label": "شي إن", "aliases": ["shein"]},
        {"label": "يوني كلو", "aliases": ["uniqlo"]},
        {"label": "سوبريم", "aliases": ["supreme"]},
        {"label": "سان لوران", "aliases": ["saint laurent", "ysl"]},
        {"label": "جيفنشي", "aliases": ["givenchy"]},
        {"label": "فالنتينو", "aliases": ["valentino"]},
        {"label": "بوس", "aliases": ["hugo boss", "boss"]},
        {"label": "غيس", "aliases": ["guess"]},
        {"label": "أمريكان إيجل", "aliases": ["american eagle"]},
        {"label": "ستراديفاريوس", "aliases": ["stradivarius"]}
    ],
}